### ISSUE TITLE
Rsync on Windows fails – lacks /cygdrive prefix

### ISSUE THREAD

**Issue by brianreavis** [mitchellh/vagrant#4073]
For more details, see #3230. No one on the vagrant team seems to be noticing it... so that's why I'm intentionally creating a duplicate issue here. Feel free to close / delete this when it is reopened.

**Comment by 1jerry** [comment]
From my testing, if you are using cygwin, use the solution by @osroot25 .

If you are using cwRsync and do _not_ have cygwin, there is no workaround *using Vagrant* except editing the source code (see https://github.com/mitchellh/vagrant/issues/3230#issuecomment-54082977).

My workaround that works for me is to bypass Vagrant altogether and use cwRsync directly.  This works for me because I am syncing a folder that hardly ever changes.  I might change it quite a few times in one day (so I have to remember step 2 below each time), but I then go weeks (or months) without any changes.  Remember that to use cwRsync you have to edit and use the cwrsync.cmd script.  Attempting to access the rsync.exe command directly or by adding it to your path will **fail**.  Step 1: I added the following line to the end of cwrsync.cmd (in the installed folder):

```
rsync -re "ssh -p 2222" /cygdrive/b/VCS/packages/ vagrant@localhost:packages --exclude ".git/"
```
Step 2:  I have a separate cmd window open that I run the cwrsync.cmd using the full path.  Then if I need to sync changes onto the VM, I activate that window, *up-arrow, return* and updating is instant!

Modifying ENV to set cygwin fix by @osroot25 doesn't work with cwRsync because when you force cygwin detection, the "vagrant ssh" command will not work because it **requires** the cygpath command in cygwin, which you won't have, so you cannot ssh into the VM.  Well you can if you use the ssh command directly with all the right options.

### the fix
To answer @mitchellh, the code pointed to by @matt-richardson looks correct.  cwRsync (and probably MSYS's rsync) *require* the /cygdrive prefix, (which seems to be a standard for posix commands on Windows).  So I think the logic should be: if Platform:windows then add the prefix.  But this is not happening.  Either the windows flag isn't being set or this code isn't being executed or the cygwin_path() isn't producing the correct result as of Vagrant 1.6.5.

**Comment by osroot25** [comment]
> if Platform:windows then add the prefix. But this is not happening. Either the windows flag isn't being set or this code isn't being executed or the cygwin_path() isn't producing the correct result as of Vagrant 1.6.5.

Then the following code fails:

    process = Subprocess.execute(
                "bash",
                "--noprofile",
                "--norc",
                "-c", "cd #{Shellwords.escape(path)} && pwd")
              return process.stdout.chomp
(lib/vagrant/util/platform.rb lines71-76 in v 1.6.5)

as I have no idea how this code-fragment works, I can't help here.

**Comment by osroot25** [comment]
haha, could it be, that 

    "cd #{Shellwords.escape(path)} && pwd"

should be

    "'cd #{Shellwords.escape(path)} && pwd'"

because -c expects a string (so the string passed to the process has to contain a string)
??

Question is, if this command can be executed with cwRsync...

**Comment by 1jerry** [comment]
Interesting..  I *do* have a bash command in the path.  I get the expected results (no prepended /cygdrive).

I found one one more interesting/annoying issue with rsync on Windows while doing further testing:

1. the rsync command from cwRsync is version 3.0.6
  1. this version *requires* the leading /cygdrive and doesn't work with just the drive (/b/some/name)
1. the rsync command from minGW (MSYS) is version 3.0.8
  1. this version works with just the drive (/b/some/name) and *will not* work with /cygdrive 
  1. unfortunately, this version, with openSSH v5.2p1 in the same path, still doesn't work with Vagrant's "synced_folder" (vague "read error)  

I see two easy solutions (for now)

1. test for "/cygdrive" on the front of hostpath.  Assume the user knows what they are doing and *do not* change hostpath at all.
1. in cygwin_path(), to get the path string, *always* try to run cygpath, then try bash, *then return unmodified* instead of returning nothing.
  1. cwRsync package includes the *cygpath.exe* command.
    1. That means that modifying ENV as suggested by @osroot25 might just work if you make sure your path includes the cygpath.exe from cwRsync/bin.
  1. MSYS version of rsync might exist *without* any bash command
    1. Although I could not get this version (3.0.8) to work for me.

**Comment by MetaMemoryT** [comment]
:+1: good research @1jerry

**Comment by rarkins** [comment]
Is there any rsync executable that "just works" with vagrant? (apart from a full cygwin install that is)

**Comment by 1jerry** [comment]
The rsync that works for me on Windows is cwRsync
<http://www.rsync.net/resources/howto/windows_rsync.html>. The important
thing is to have the compatible ssh.exe on your path.  The ssh and rsync
commands that come with cwRsyc are both from 2009, but they work.  You *can*
run rsync and tell it which ssh.exe to use, but that won't help when using
it from Vagrant, so the ssh.exe from the cwRsync folder *must* be found in
your PATH in order for the rsync command to find it.

HTH

-- 
Jerry
--

**Comment by bizmate** [comment]
I have seen this problem in a colleagues' machine where the rsync version provided by cygwin is 3.1.1.  I have given him the binaries from my local machine running rsync 3.0.9 and it all suddenly worked.

Looks like a problem that vagrant might not solve easily unless versions are checked. Happy to run some tests if it can help troubleshooting

**Comment by chedaroo** [comment]
@1jerry thanks for your efforts regarding this, after setting the os detect manually my final issue was incompatibility between rsync and ssh as noted by yourself in https://github.com/mitchellh/vagrant/issues/4073#issuecomment-70341002 and  https://github.com/mitchellh/vagrant/issues/4073#issuecomment-77020266

**Comment by agungsijawir** [comment]
thank you @1jerry for your research. i successfully manage to install and run vagrant properly when using rsync  version 3.0.6  protocol version 30

thanks

**Comment by Hunternnm** [comment]
The second day of trying to fix a mistake - and no way out. I downloaded from the site configuration puphpet.com to work with symfony2 chose rsynk as others are slow. Download and install cygwin and established through rsynk added them to the variable PATH. In D:\dev\vagrant\puphpet\vagrant\Vagrantfile-local I added a line
ENV["VAGRANT_DETECTED_OS"] = ENV["VAGRANT_DETECTED_OS"].to_s + " cygwin"
But when you start still an error -
==> default: Rsyncing folder: /cygdrive/d/dev/vagrant/webroot/ => /var/www
==> default:   - Exclude: [".vagrant/", ".git/"]
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /cygdrive/d/dev/vagrant/webroot/
Guest path: /var/www
Command: rsync --verbose --archive -z --chmod=ugo=rwX --no-perms --no-owner --no
-group --rsync-path sudo rsync -e ssh -p 2222 -o StrictHostKeyChecking=no -o Use
rKnownHostsFile=/dev/null -i 'd:/dev/vagrant/.vagrant/machines/default/virtualbo
x/private_key' --exclude .vagrant/ --exclude .git/ /cygdrive/d/dev/vagrant/webro
ot/ vagrant@127.0.0.1:/var/www
Error: Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of know
n hosts.
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [Receive
r=3.1.0]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=
3.1.1]

win7x64, vagrant 1.7.2

**Comment by jeancasman** [comment]
@hunternnm

Got similar problem with win7x64, vagrant 1.7.4, cygwin (rsync + ssh) and Git Bash.
After struggling for hours and reading proposed solutions on GitHub, this is what worked for me:

* Add ENV["VAGRANT_DETECTED_OS"] = ENV["VAGRANT_DETECTED_OS"].to_s + " cygwin" to Vagrantfile.
* Add cygwin to PATH.
* Use windows command line instead of Git Bash.

Hope this can help.

**Comment by vteivans** [comment]
**My solution for GitBash + cygwin + Vagrant**

After installing cygwin, add to your `.bashrc`:
```bash
# Add cygwin to path for rsync:
export PATH=$PATH:/c/cygwin/bin  # your cygwin path
# Tell vagrant, we have cygwin:
export VAGRANT_DETECTED_OS=cygwin
```

**Comment by thePanz** [comment]
fixed with @vteivans comment (I am using just plain Cygwin, no GitBash)

**Comment by WRidder** [comment]
Confirmed working on Windows 10 using cygwin (rsync + openssh); making sure cygwin is before GIT in PATH and following this guide: http://micahasmith.github.io/2015/01/22/coreos-vagrant-windows-file-share/.

**Comment by XedinUnknown** [comment]
I use GitBash without Cygwin. Still not sure what I should do. Any suggestions?

**Comment by akaSStalkALEX** [comment]
The error is still present in version 1.7.4. "/cygdrive" was added, cygwin was installed and rsync, openssh inside. All variables in path exist. Nothing helped. What else should I do? Os: win 10. I

**Comment by jamesvl** [comment]
While not _directly_ related to this issue: cygwin rsync (and I think also cwRysnc) will both fail to run on the latest Windows 10 "major update" (from Nov. 12 2015). I had the cygwin rsync working flawlessly on Windows 8.1 and Windows 10 (and latest versions of Vagrant and Virtual Box); then it failed after applying the Windows service pack.

Errors are along the lines of
```
rsync 6132 C:\Tools_Data\utils\cygwin64\bin\rsync.EXE: *** fatal error in forked process - fork: can't reserve memory for parent stack 0x600000 - 0x800000, (child has 0x400000 - 0x600000), Win32 error 487
    529 [main] rsync 6132 cygwin_exception::open_stackdumpfile: Dumping stack trace to rsync.EXE.stackdump
      1 [main] rsync 4308 fork: child -1 - forked process 6132 died unexpectedly, retry 0, exit code 0x100, errno 11
rsync: fork: Resource temporarily unavailable (11)
rsync error: error in IPC code (code 14) at pipe.c(65) [sender=3.1.1]
```

I'm investigating how best to report the issue to cygwin.

**Comment by mitchellh** [comment]
OKAY! This should _finally_ be fixed (I hope) with Vagrant 1.8. We now automatically convert all paths for rsync on Windows to the cygwin path format since every implementation of cygwin requires that.

**Comment by kurttomlinson** [comment]
I'm running into the same problem as @jamesvl after updating to Windows 10 Threshold 2.

    ==> default: Rsyncing folder: /cygdrive/c/Users/Kurt/.../ => /www/...
          4 [main] rsync 14940 C:\cygwin64\bin\rsync.EXE: *** fatal error in forked process - fork: can't reserve memory for parent stack 0x600000 - 0x800000, (child has 0x400000 - 0x600000), Win32 error 487
       3301 [main] rsync 14940 cygwin_exception::open_stackdumpfile: Dumping stack trace to rsync.EXE.stackdump
          0 [main] rsync 4680 fork: child -1 - forked process 14940 died unexpectedly, retry 0, exit code 0x100, errno 11
    There was an error when attempting to rsync a synced folder.
    Please inspect the error message below for more info.

    Host path: /cygdrive/c/Users/Kurt/.../
    Guest path: /www/...
    Command: rsync --verbose --archive --delete -z --copy-links --chmod=ugo=rwX --no-perms --no-owner --no-group --rsync-path sudo rsync -e ssh -p 2222 -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i 'C:/Users/Kurt/...' --exclude .vagrant/ /cygdrive/c/Users/Kurt/.../ vagrant@127.0.0.1:/www/...
    Error:       4 [main] rsync 14940 C:\cygwin64\bin\rsync.EXE: *** fatal error in forked process - fork: can't reserve memory for parent stack 0x600000 - 0x800000, (child has 0x400000 - 0x600000), Win32 error 487
       3301 [main] rsync 14940 cygwin_exception::open_stackdumpfile: Dumping stack trace to rsync.EXE.stackdump
          0 [main] rsync 4680 fork: child -1 - forked process 14940 died unexpectedly, retry 0, exit code 0x100, errno 11
    rsync: fork: Resource temporarily unavailable (11)
    rsync error: error in IPC code (code 14) at pipe.c(65) [sender=3.1.1]

**Comment by kurttomlinson** [comment]
I fixed my issue, I had the 64-bit version of cygwin installed. I deleted that and installed the 32-bit version instead. Now it's working fine again on Windows 10. FYI @jamesvl

**Comment by stanicek** [comment]
Thanks @kurttomlinson ! Downgrading cygwin from 64-bit to 32-bit version also worked for me on the latest Windows 10 update.

**Comment by lewins** [comment]
Downgrading to 32-bit didnt worked.
Solution for me was downloading cwRsync https://www.itefix.net/content/cwrsync-free-edition
and placed all files into `C:\Git\mingw64\bin`

**Comment by arthuroy** [comment]
I had the same issue, fork: can't reserve memory for parent stack, using rsync in msys2-x86_64-20150916.exe from http://msys2.github.io/ on Microsoft Windows 11.10.10.10586.

```bash
0 [main] rsync 8900 C:\msys64\usr\bin\rsync.EXE: *** fatal error in forked process - fork: can't reserve memory for parent stack 0x600000 - 0x800000, (child has 0x400000 - 0x600000), Win32 error 487
```

And I fixed my issue by using the 32-bit msys2-i686-20150916.exe (32-bit) instead.
Now I can see that rsync works as expected:

```bash
==> centos-atomic-host-01: Configuring and enabling network interfaces...
==> centos-atomic-host-01: Rsyncing folder: /d//vagrant-docker-ansible/ => /home/vagrant/sync
```

**Comment by firestalk** [comment]
In case of someone will still have an issue after previous instructions, don't forget to install rsync and openssh in msys2 32bit using pacman.

**Comment by arthuroy** [comment]
Guess the reason why rsync from msys2-x86_64 failed is **vagrant is running 32-bit mode**. So you have to use 32-bit msys2's rsync.

**Comment by firestalk** [comment]
What weird is that I used msys2 64 bit before and it worked flawlessly. Problems started after windows 10 recent upgrade.

**Comment by arthuroy** [comment]
@firestalk Thanks for your information.
I wanna use msys2 64-bit as well, but... :trollface:
Using msys2 32-bit is a workaround on Windows 10 build 10586 (Threshold 2).

**Comment by rekcodocker** [comment]
Here's a note from 16-12-2015.   
The bug is still there.

I am using cygwin 64 bit, I am not looking forward to downgrading. 
And the fix at line 74 still works.  

It seems like the cygwin-detection of this helper script is faulty and either fails to detect cygwin, or fails to construct the proper path.

This error occurs when using a Debian-box (jesse, 8.2.2), but not with Ubuntu (ubuntu still shares directory with vboxsf).

Please... fix this. This error stems from 2014, it's a year and a half old.

**Comment by arthuroy** [comment]
`rsync` doesn't work on Vagrant 1.8.0, was ok on 1.7.4... too bad...

rsync & openssh from 32-bit msys2-i686-20150916.exe (32-bit)

```bash
    coreos-01: Rsyncing folder: /d/vagrant-lab/ => /vagrant
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /d/vagrant-lab/
Guest path: /vagrant

Command: rsync --verbose --rsync-path='sudo rsync' --archive --delete -zz --chmod=ugo=rwX --no-perms --no-owner --no-group --rsync-path sudo rsync -e ssh -p 2222 -o ControlMaster=auto -o ControlPath=C:/msys32/tmp/ssh.702 -o ControlPersist=10m -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i 'C:/Users/<user_name>/.vagrant.d/insecure_private_key' --exclude .vagrant/ /d/vagrant-lab/ core@127.0.0.1:/vagrant
Error: Warning: Permanently added '[127.0.0.1]:2222' (ED25519) to the list of known hosts.
mm_receive_fd: no message header
process_mux_new_session: failed to receive fd 0 from slave
mux_client_request_session: read from master failed: Connection reset by peer
Failed to connect to new control master
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.1]
```

**Comment by adiospeds** [comment]
@jeancasman 's solution worked for me - especially the switch to windows cmd just for vagrant up part :+1:
