### ISSUE TITLE
Insecure key replacement should work better with config.ssh.private_key_path set

### ISSUE THREAD

**Issue by akloeber** [mitchellh/vagrant#4967]
In my Vagrantfile I have got the following configuration:

    config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']

The first private key is the insecure default key only used for bootstrapping to create a dedicated `deploy` user. After bootstrapping this `deploy` user is used for provisioning with the second private key.

On Vagrant 1.6.3 that worked fine and both keys were handed over to ansible (output from running in verbose mode):

    <localhost> ESTABLISH CONNECTION FOR USER: deploy
    <localhost> REMOTE_MODULE setup
    <localhost> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'IdentityFile=/Users/me/.ssh/id_rsa', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/me/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=2222', '-o', 'IdentityFile="/Users/me/.vagrant.d/insecure_private_key"', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=deploy', '-o', 'ConnectTimeout=10', 'localhost', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1418562345.93-241929617693436 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1418562345.93-241929617693436 && echo $HOME/.ansible/tmp/ansible-tmp-1418562345.93-241929617693436'"]
    <localhost> PUT /var/folders/zb/zjxy59t53514yy4zf1707rq40000gn/T/tmpkMiKNS TO /home/deploy/.ansible/tmp/ansible-tmp-1418562345.93-241929617693436/setup
    <localhost> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'IdentityFile=/Users/me/.ssh/id_rsa', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/me/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=2222', '-o', 'IdentityFile="/Users/me/.vagrant.d/insecure_private_key"', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=deploy', '-o', 'ConnectTimeout=10', 'localhost', u"/bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/deploy/.ansible/tmp/ansible-tmp-1418562345.93-241929617693436/setup; rm -rf /home/deploy/.ansible/tmp/ansible-tmp-1418562345.93-241929617693436/ >/dev/null 2>&1'"]
    ok: [main-test]

With current Vagrant 1.7.1 this does not work anymore as only some private key at `.vagrant/machines/main-test/virtualbox/private_key` gets handed over to ansible:

    <localhost> ESTABLISH CONNECTION FOR USER: deploy
    <localhost> REMOTE_MODULE setup
    <localhost> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/me/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=2222', '-o', 'IdentityFile="/Users/me/repo/.vagrant/machines/main-test/virtualbox/private_key"', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=deploy', '-o', 'ConnectTimeout=10', 'localhost', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1418561697.39-154151814748935 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1418561697.39-154151814748935 && echo $HOME/.ansible/tmp/ansible-tmp-1418561697.39-154151814748935'"]

That provokes a `Permission denied (publickey,password).` error. Direct SSH access via `ssh -i /Users/me/.ssh/id_rsa deploy@vagrant.local` does work fine.

**Comment by dragon788** [comment]
@ploxiln You could try vagrant reload --provision or vagrant halt and then vagrant up --provision to force a provision without destroying.

**Comment by mitchellh** [comment]
Fixed!

**Comment by lonniev** [comment]
Is there a readme/howto now for how to use the new behavior to initially provide the default, insecure ssh key and to then provide a chosen secure private key such that a mere user can do the initial vagrant up from a base box and then the daily vagrant ups of the provisioned VMs -- without having to modify the Vagrantfile or shuffle keys in personal directories?

I get the idea but the practice at the moment (as we transition through Vagrant 1.7.4) is a bit of trial and error.

(It might matter that my preferred host is a Mac and our guests are both Linux and Windows. Often, this combination is not well tested in Vagrant/Chef land.)

**Comment by gbell12** [comment]
Something's either still not right or unclear.  I would hope that the key pointed at by config.ssh.private_key_path would be used when the insecure key was replaced.  In other words, as the new key.  

This way vagrant can get in the first time the machine's up'd (the insecure key is used, even though it's not in config.ssh.private_key_path), and I can get in later, after the insecure key is replaced with my key.

**Comment by lonniev** [comment]
I haven’t looked at this beyond setting the option to the insecure key or to a private key. That ignorance disclosed, I suggest that it would be useful if the `config.ssh.private_key_path` offered a list of try-me-in-order keys. Vagrant would start with the first and work to the last trying the keys until it found one that opens the door or it has no more to try. Then, as users we would provide both the initial insecure key followed by one or more lesser-known private keys. With this approach, we could both vagrant up new base images, provision recent images, and use images operationally over time all without ever having to alter the Vagrantfiles.

-- 
Lonnie VanZandt
303-900-3048

On 30 August 2015 at 05:30:39, gbell12 (notifications@github.com) wrote:

Something's either still not right or unclear. I would hope that the key pointed at by config.ssh.private_key_path would be used when the insecure key was replaced. In other words, as the new key.

This way vagrant can get in the first time the machine's up'd (the insecure key is used, even though it's not in config.ssh.private_key_path), and I can get in later, after the insecure key is replaced with my key.

**Comment by gbell12** [comment]
Agreed.  I would like to see the default key tried implicitly, rather than have to specify .vagrant/machines/etc/etc

I would also think a new variable useful, say config.ssh.new_private_key, which would be what the key was SET to on the target machine (rather than the current behavior of generating a new pair).
