### ISSUE TITLE
Name should be supported for `vagrant up --provision-with`

### ISSUE THREAD

**Issue by ches** [mitchellh/vagrant#5139]
Given a minimal example `Vagrantfile` like:

```ruby
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'chef/ubuntu-14.04'

  config.vm.provision 'bootstrap', type: :shell, inline: 'echo BOOTSTRAP!'
  config.vm.provision 'deploy',    type: :shell, inline: 'echo DEPLOY!'
end
```

I expect `vagrant up --provision-with bootstrap` to work intuitively, but instead:

    $ vagrant up --provision-with bootstrap
    'bootstrap' is not a known provisioner. Please specify a valid provisioner.

It appears that the [command validation for `up` in `StartupMixins`][1] only respects the *types* of registered provisioner plugins, not user-supplied names. Digging in the code and looking back at the changes in #4700, to my understanding so far there currently isn't a mapping of names to provisioner types or instances available except [during a provision action][2] when the [stuff from `MixinProvisioners`][3] is called, or else by grabbing instances of `VagrantConfigProvisioner` from a specific machine like `env[:machine].config.vm.provisioners`.

I'm not totally clear on initialization order yet, but at the stage of validating the up command I'd assume we'd have to iterate over machines to get the provisioner names set on them, or come up with a cleaner way of achieving that if one doesn't already exist. If anyone can point me in the right direction on that I will try to cook up a patch.

[1]: https://github.com/mitchellh/vagrant/blob/d482e0ca106071cf42eea8aab9ab22323d1aa3d9/plugins/commands/up/start_mixins.rb#L29
[2]: https://github.com/mitchellh/vagrant/blob/ee0423b792c338aad45118dcebb4c261cd20b119/lib/vagrant/action/builtin/provision.rb#L75
[3]: https://github.com/mitchellh/vagrant/blob/ee0423b792c338aad45118dcebb4c261cd20b119/lib/vagrant/action/builtin/mixin_provisioners.rb

**Comment by tacoben** [comment]
Can someone update the documentation then?

http://docs.vagrantup.com/v2/cli/provision.html

it CLEARLY states:

"The arguments to --provision-with can be the provisioner type (such as "shell") or the provisioner name (such as "bootstrap" from above)."

which is wrong.

**Comment by ches** [comment]
@tacoben That document is technically correct, it *does* work for the `provision` subcommand. User-supplied name *does not* work for `up` (and it'd be really nice if it did).

**Comment by gaberger** [comment]
Is this an enhancement or a bug?

**Comment by tacoben** [comment]
@ches you are correct - i was getting confused.

i just confirmed it.

**Comment by schkovich** [comment]
You are not the only one who get confused. **It is confusing** that the same option e.g. ```--provision-with``` behaves differently with ```up``` and ```provision``` commands.

I have an use case in which provisioning has to be done in two steps: Software installed requires user action at some point. I could do:
```
vagrant up --no-provision
vagrant provision --provision-with a, b
vagrant ssh
# perform authentication and exit
vagrant provision --provision-with c, d, e
```
but it will be more elegant to do:
```
vagrant up --provision-with a, b
vagrant ssh
# perform authentication and exit
vagrant provision --provision-with c, d, e
```

**Comment by lattwood** [comment]
I ran into this issue as well, found this github issue while googling.

Possible fix: `vagrant up --provision-with` ought to be `vagrant up --provision-with-type(s)` if there's no functionality change.

**Comment by b-long** [comment]
:+1: +1 for the `--provision-with` on `vagrant up`.  I also have a use case where I need to do : 
```shell
vagrant up --no-provision
vagrant provision --provision-with a,b
vagrant provision --provision-with c,d
```

Now, in part this is my fault.  However, I'm re-using some Puppet modules that I don't fully understand and it's in setting up a rather complex multi-node environment.  The workflow I'm using is repeatable and works.  

I would put my support behind any additional fine-grained control of provisioners :smile:

**Comment by zicai** [comment]
I ran into this issue as well, found this github issue while googling. :cry:

**Comment by kevinohara80** [comment]
Ugh, me too. :disappointed:

**Comment by avdd** [comment]
@gaberger it's a bug, as the indended behaviour is to work on the 'up' command:

https://github.com/mitchellh/vagrant/pull/4700#issue-46697567

    --provision-with flag on up, reload, etc. works with names as well as IDs

**Comment by mitchellh** [comment]
Fixed via #5981

**Comment by dgonano** [comment]
I'm running 2.01 and still having this issue, I can specify `shell` but not same `s`. Same deal with up and provision. Did this get reverted or something?

**Comment by briancain** [comment]
@dgonano - no, this should still work. If you're experiencing a problem please open an issue and we'll take a look. Thanks!

**Comment by dgonano** [comment]
@briancain Super busy but will try to get a log for you. How do I get verbose output?

**Comment by dragon788** [comment]
You could also run `vagrant up --debug > some-log.txt` and then upload the .txt to a gist and link it here.
