### ISSUE TITLE
uninitialized constant Vagrant::Action::Builtin::MixinSyncedFolders

### ISSUE THREAD

**Issue by aidanmorgan** [mitchellh/vagrant#5196]
I have pulled the latest from master and built according to the documentation, when I attempt to use Vagrant I now get an error:

    Vagrant failed to initialize at a very early stage:
    
    The plugins failed to load properly. The error message given is
    shown below.

    uninitialized constant Vagrant::Action::Builtin::MixinSyncedFolders

I have tried disabling the use of synced folders from my Vagrantfile, however the error still occurs.

Host: Windows 8.1
Provider: HyperV
Guest: Windows Server 2012 R2

**Comment by aidanmorgan** [comment]
Looks like this is a duplicate of #5149

**Comment by aidanmorgan** [comment]
I have cleaned my Ruby environment (using the nixpulvis/5042764 gist) and rebuilt from master - issue is still occurring

**Comment by matt-richardson** [comment]
This is also happening for me on the released version vagrant 1.7.2.
I've run `vagrant plugin update` and it still happens.
~~~~~
$ vagrant plugin list
vagrant-omnibus (1.4.1)
vagrant-share (1.1.3, system)
vagrant-vbguest (0.10.0)
vagrant-vsphere (1.0.1)
vagrant-windows (1.6.0)
vagrant-winrm (0.4.0)
~~~~

Host: Windows 8.1

**Comment by matt-richardson** [comment]
Uninstalling all plugins helped... Then re-adding them one by one, it seems the issue was caused by vagrant-windows, which is no longer needed in vagrant 1.6+.
So, for me, this is resolved...

**Comment by aidanmorgan** [comment]
I've cleaned all of my gems and still have this problem. Is there something I else I should do?

**Comment by sethvargo** [comment]
@aidanmorgan I am sorry you are having problems. Can you please show the output of `vagrant plugin list`?

**Comment by aidanmorgan** [comment]
@sethvargo sorry - I blew all my gems and gemspecs away and it looks like it is working for me - I can only assume I missed something the first time I cleaned up.

**Comment by soderlind** [comment]
vagrant 1.7.2 on mac os x 10.10.1, running `vagrant plugin uninstall vagrant-windows` fixed this for me.

**Comment by cristobal** [comment]
Yup running ` vagrant plugin uninstall vagrant-windows` worked for me too :)
@soderlind :+1:

**Comment by volehare** [comment]
vagrant 1.7.2 on mac os x 10.10.1, running vagrant plugin uninstall vagrant-windows fixed this for me too. :+1:

**Comment by AnthonyMastrean** [comment]
I'm experiencing the same on a clean installation.

Windows 7 x64 Pro
Vagrant 1.7.2

```
$ vagrant plugin list
vagrant-hosts (2.1.2)
vagrant-share (1.1.3, system)
vagrant-windows (1.5.1)
```

**Comment by Michel73** [comment]
It doesn't works for me. 
Host: Windows 7 x64 Pro
```
$>vagrant plugin install vagrant-windows
Installing the 'vagrant-windows' plugin. This can take a few minutes...
Installed the plugin 'vagrant-windows (1.6.0)'!

$>vagrant up
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

uninitialized constant Vagrant::Action::Builtin::MixinSyncedFolders

$>vagrant plugin uninstall vagrant-windows
Uninstalling the 'vagrant-windows' plugin...

$>vagrant up
vagrant-windows missing, please install the vagrant-windows plugin!
Run this command in your terminal:
vagrant plugin install vagrant-windows

$>vagrant -v
Vagrant 1.7.2
```

**Comment by cmjchrisjones** [comment]
I am facing the same issue as @Michel73 trying to 'vagrant up' a Windows box from opentable/win-8-pro-amd64-nocm

**Comment by brimworks** [comment]
I'm also seeing this on Mac when I install the vagrant-windows plugin. If I remove the error handling then I can get this stack trace:

```
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/provisioners/chef/provisioner/chef_solo.rb:18:in `<class:ChefSolo>': uninitialized constant Vagrant::Action::Builtin::MixinSyncedFolders (NameError)
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/provisioners/chef/provisioner/chef_solo.rb:15:in `<module:Provisioner>'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/provisioners/chef/provisioner/chef_solo.rb:13:in `<module:Chef>'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/provisioners/chef/provisioner/chef_solo.rb:12:in `<module:VagrantPlugins>'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/provisioners/chef/provisioner/chef_solo.rb:11:in `<top (required)>'
        from /Users/bmaher/.vagrant.d/gems/gems/vagrant-windows-1.6.0/lib/vagrant-windows/monkey_patches/plugins/provisioners/chef/provisioner/chef_solo.rb:1:in `require'
        from /Users/bmaher/.vagrant.d/gems/gems/vagrant-windows-1.6.0/lib/vagrant-windows/monkey_patches/plugins/provisioners/chef/provisioner/chef_solo.rb:1:in `<top (required)>'
        from /Users/bmaher/.vagrant.d/gems/gems/vagrant-windows-1.6.0/lib/vagrant-windows/plugin.rb:37:in `require_relative'
        from /Users/bmaher/.vagrant.d/gems/gems/vagrant-windows-1.6.0/lib/vagrant-windows/plugin.rb:37:in `<top (required)>'
        from /Users/bmaher/.vagrant.d/gems/gems/vagrant-windows-1.6.0/lib/vagrant-windows.rb:24:in `require'
        from /Users/bmaher/.vagrant.d/gems/gems/vagrant-windows-1.6.0/lib/vagrant-windows.rb:24:in `<top (required)>'
        from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/runtime.rb:76:in `require'
        from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
        from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/runtime.rb:72:in `each'
        from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/runtime.rb:72:in `block in require'
        from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/runtime.rb:61:in `each'
        from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/runtime.rb:61:in `require'
        from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler.rb:134:in `require'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant.rb:273:in `<top (required)>'
        from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:105:in `require'
        from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:105:in `<main>'
```

**Comment by brimworks** [comment]
To work around this problem, I commented out this line:

```ruby
require_relative "monkey_patches/plugins/provisioners/chef/provisioner/chef_solo"
```

of this file:

    ~/.vagrant.d/gems/gems/vagrant-windows-1.6.0/lib/vagrant-windows/plugin.rb

**Comment by ThomasFeher** [comment]
The problem of @Michel73 and @cmjchrisjones seems to be due to wrong/old configuration by the creator of this specific box. To fix this go to "~/.vagrant.d/boxes/opentable-VAGRANTSLASH-win-7-professional-amd64-nocm/1.0.0/virtualbox/",  open the file "Vagrantfile" and delete the following lines:

    if !Vagrant.has_plugin?('vagrant-windows')
      puts "vagrant-windows missing, please install the vagrant-windows plugin!"
      puts "Run this command in your terminal:"
      puts "vagrant plugin install vagrant-windows"
      exit 1
    end

**Comment by joanluk** [comment]
vagrant 1.7.2 on mac os x 10.10.3, running vagrant plugin uninstall vagrant-windows fixed.

**Comment by varhub** [comment]
**Confirm solution** of @ThomasFeher for *opentable/win-8-core-i386-nocm* (issue: inplace check)
Host: Vagrant 1.7.2/Windows 8.1
