### ISSUE TITLE
Having to delete tmp images when: HTTP server doesn't seem to support byte ranges. Cannot resume

### ISSUE THREAD

**Issue by sergiotapia** [mitchellh/vagrant#5295]
> Related: https://github.com/mitchellh/vagrant/issues/4479#issuecomment-73053652
---

Still an issue for me.

* Vagrant 1.7.2
* Mac OSX Yosemite

---

The download timed out, and then when I ran the `vagrant up` command again to download it says: 

> HTTP server doesn't seem to support byte ranges. Cannot resume

I think Vagrant should be smart enough to toss the tmp data for that image, if the response server does not support byte ranges. Thanks!

**Comment by mitchellh** [comment]
This is fixed in master.

**Comment by tanji** [comment]
Upgrading to 1.7.4 didn't fix the issue:

# tanj at macpro in ~/Vagrant/debian-jessie [14:11:02]
$ vagrant -v
Vagrant 1.7.4

# tanj at macpro in ~/Vagrant/debian-jessie [14:11:04]
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'debian/jessie64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'debian/jessie64'
    default: URL: https://atlas.hashicorp.com/debian/jessie64
==> default: Adding box 'debian/jessie64' (v8.1.0) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/debian/boxes/jessie64/versions/8.1.0/providers/virtualbox.box
==> default: Box download is resuming from prior download progress
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

HTTP server doesn't seem to support byte ranges. Cannot resume.

**Comment by gsingh93** [comment]
Same issue with the latest version on Mac OS X.

**Comment by boneskull** [comment]
This is not fixed.

**Comment by mitchellh** [comment]
Thanks, we reopend #4479 to take a look.
