### ISSUE TITLE
v1.7.3 Cannot find puppet install on Windows

### ISSUE THREAD

**Issue by goffinf** [mitchellh/vagrant#5943]
Cool 1.7.3 is released and has Puppet 4 support. Unfortunately there appears to be a problem finding the Puupet 4 install on the guest. I can assure you it's definitely there (in the standard location) and on the PATH, which I confirmed by running 'puppet apply ...' in a shell provisioner. This is the error message ...

```
E:\Data\aws\vagrant\nexus>vagrant provision --provision-with puppet
==> nexus: Running provisioner: puppet...
The puppet binary appears not to be in the PATH of the guest. This could be because the PATH is not properly setup or perhaps Puppet is not installed on this guest. Puppet provisioning can not continue without Puppet properly installed.
```

I tried adding the binary_path property as in ...

```ruby
puppet.binary_path="C:/Program Files/PuppetLabs/Puppet/bin"
```

... but this produced a similar error ...

```
E:\Data\aws\vagrant\nexus>vagrant provision --provision-with puppet
==> nexus: Running provisioner: puppet...
The C:/Program Files/PuppetLabs/Puppet/bin/puppet binary appears not to be in the PATH of the guest. This could be because the PATH is not properly setup or perhaps Puppet is not installed on this guest. Puppet provisioning can not continue without Puppet properly installed.
```

I played around with different variants of binary_path, but to no avail.

Here is the puppet provisioner config from my VagrantFile ...

```ruby
nexus.vm.provision "puppet" do |puppet|
  puppet.module_path = "E:/Data/git/mycomp.digital.aws.puppet/puppet/modules"
  #puppet.binary_path="C:/Program Files/PuppetLabs/Puppet/bin"
  puppet.manifests_path = "E:/Data/git/mycomp.digital.aws.puppet/puppet/manifests"
  puppet.environment="production"
  puppet.environment_path="C:\ProgramData\PuppetLabs\code\environments"
  puppet.manifest_file = "site.pp"
  puppet.hiera_config_path = "../puppet/hiera/hiera.yaml"
  puppet.options = "--node_name_value=sonatype_nexus"
  #puppet.options = "--verbose --debug --trace"
end
```

**Comment by mitchellh** [comment]
I wonder if this can be fixed by simply not verifying the binary if the full path is given. It looks like the `command -v` check on Windows isn't working with a complete path.

**Comment by lmayorga1980** [comment]
@mitchellh I believe I have the same issue under Windows 2012R2 Guest. 

 https://github.com/mitchellh/vagrant/issues/5615

**Comment by goffinf** [comment]
@lmayorga1980 you certainly do. Windows 2012R2 was the context that I was also using.

**Comment by agarstang** [comment]
@ferventcoder points out it's a problem with commit [3a2a9a3b948f1dc7f8dc7a49494e4c48eaf5a5e6](https://github.com/mitchellh/vagrant/commit/3a2a9a3b948f1dc7f8dc7a49494e4c48eaf5a5e6) not accounting for Windows Guests.

**Comment by ferventcoder** [comment]
It should still work given passing the binary path - the default is what I was hoping to adjust for Windows.

**Comment by mitchellh** [comment]
Fixed in master, will be in 1.7.4

**Comment by ferventcoder** [comment]
It might likely be that it is not recognizing puppet.bat though.

**Comment by philipwigg** [comment]
I think this issue still exists in 1.7.4 - I think I can see what the problem is and I will submit a PR.

**Comment by shanemgrey** [comment]
I'm running into this also.  Using on osx with virtualbox and same everything on windows 10 with Hyper-V as the provider.  It fails with this puppet path message on Hyper-V.  

I edited the puppet.rb file as in the PR from @philipwigg and am still getting the same issue.

**Comment by huemans** [comment]
Having the same problem but on mac. Details here 
https://github.com/mitchellh/vagrant/issues/1737

**Comment by frusswur** [comment]
When you have Windows 7 as a guest OS than the cause of the problem is a Vagrant bug which can be solved with the following workaround. The reason for this bug is, that Windows 7 uses the Powershell Version 2.0, which uses another syntax of the command `where`. When you run this Powershell script before the puppet provisioner runs. It sets an alias for the `where ` Command to `where.exe` command.
```
$ProfileFile = 'profile.ps1'
$ProfileFilePath = Join-Path $PsHome $ProfileFile

New-Item $ProfileFilePath -type file -force -value "del alias:where -Force; Set-Alias where where.exe"
```

**Comment by ferventcoder** [comment]
All versions of PowerShell override the where command. 

~~~sh
C:\> get-alias where

CommandType     Name                                               ModuleName
-----------     ----                                               ----------
Alias           where -> Where-Object


C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      3.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.34209
BuildVersion                   6.2.9200.16398
PSCompatibleVersions           {1.0, 2.0, 3.0}
PSRemotingProtocolVersion      2.2

~~~

**Comment by ferventcoder** [comment]
Always better to call where.exe 👍  

Deleting the alias unconditionally and setting it to where.exe also works. You can also change the alias this way instead:

~~~powershell
Set-Alias where where.exe -Force -Scope Global -Option AllScope
~~~

But your method may be more compliant against all versions of PowerShell, I've only tested the above in v3+.

**Comment by ferventcoder** [comment]
The docs only go back to v3 (but usually mention when things are not compliant with v2) -https://technet.microsoft.com/en-us/library/hh849938(v=wps.620).aspx

**Comment by tehmaspc** [comment]
I have not had any luck this week getting Puppet provisioner to work w/ Vagrant 1.8.1 - even w/ these fixes in place. I did build yesterday a 1.8.2-dev env to test if that fixes the issues and it does - but baring a 1.8.2 release anytime soon - does anyone on this thread have a full working example of getting say a windows2012r2 system provisioned properly with Puppet w/ 1.8.1?

Thanks a bunch!
Tehmasp

cc @ferventcoder

**Comment by ferventcoder** [comment]
I have it working, but I don't remember if I edited the vagrant install directly or not (I think I did).

**Comment by ferventcoder** [comment]
I'm running examples all the time, so I know I have it working.

**Comment by tehmaspc** [comment]
@ferventcoder good to hear; if you have any example you could pop into a gist - I would be very grateful.

Thanks,
Tehmasp

**Comment by tehmaspc** [comment]
huzzah - 1.8.3 is out! thanks @mitchellh et al!!!

**Comment by ferventcoder** [comment]
For me it was a small change that had already been addressed - the where.exe change I believe.

**Comment by tehmaspc** [comment]
@ferventcoder - cool ; thanks for following up; i must have not done something properly. Granted this week was a crash course of powershell for me as well :)
