### ISSUE TITLE
The WinRM ready? method raises an error instead of returning false

### ISSUE THREAD

**Issue by Sharpie** [mitchellh/vagrant#6356]
The following Vagrantfile includes a plugin which defines a command that attempts to print whether a VM can be communicated with:

```ruby
class TestCommand <Vagrant.plugin(2, :command)
  def execute
    with_target_vms(@argv) do |vm|
      puts "#{vm.name} #{vm.communicate.ready?}"
    end
  end
end

class TestPlugin < Vagrant.plugin('2')
  command(:running) do
    TestCommand
  end
end

Vagrant.plugin("2").manager.register(TestPlugin)

Vagrant.configure("2") do |config|
  config.vm.define 'posix-vm' do |node|
    # `vagrant running posix-vm` executes fine.
    node.vm.communicator = :ssh
  end

  config.vm.define 'windows-vm' do |node|
    # `vagrant running windows-vm` throws an error.
    node.vm.communicator = :winrm
  end
end
```

Executing `vagrant running windows-vm` throws an error:

```
vagrant running windows-vm
The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.
```

I expect the return value to be `false`, as is the case with the SSH communicator used by `vagrant running posix-vm`:

```
vagrant running posix-vm
posix-vm false
```

**Comment by Sharpie** [comment]
This example fails with Vagrant v1.7.4, but succeeds with v1.6.5, which suggests a regression of some sort in the WinRM communicator.

**Comment by RyanJarv** [comment]
I'm experiencing this issue as well

**Comment by RyanJarv** [comment]
The ssh communicator is communicator is catching Vagrant::Errors::VagrantError for ready? so this is what I'm doing to work around this issue atm.

https://github.com/RyanJarv/vagrant/commit/d46c61f613ecc3f73f95c6ef9a4050e6b329996b

**Comment by sethvargo** [comment]
Hi all,

Thank you for reporting this. This has been fixed in 1e84cc4. Thanks!

**Comment by Sharpie** [comment]
@sethvargo This is still an issue in Vagrant 1.8.1. The WinRM `ready?` method is throwing an error instead of returning `false` as the SSH `ready?` method does.

**Comment by Sharpie** [comment]
@sethvargo Can we re-open this issue now that #7028 has been closed?

**Comment by Sharpie** [comment]
@sethvargo Ping again. Could this be re-opened? This issue is still present in the latest Vagrant release.
