### ISSUE TITLE
Provision of aws windows image fails on chef-solo start

### ISSUE THREAD

**Issue by psimonovsk** [mitchellh/vagrant#6418]
Hi.
I am trying to run fairly simple vagrant bootstrup, that have to create aws windows machine and run their test chef_solo cookbook. Cookbook is "hello world" style (it simply performs touch of file - simply to give indication, that chef actually worked).

```ruby
require File.expand_path('aws/aws_credentials.rb')
Vagrant.configure("2") do |config|
	config.vm.guest = :windows
	config.vm.communicator = :winrm
	config.vm.synced_folder ".", "/vagrant", type: "winrm", :disabled => true
	config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
	config.vm.box = "dummy"
	# Admin user name and password
    config.winrm.username = "vagrant"
    config.winrm.password = "maypass" 
	#config.winrm.password = "vagrant" 
 	config.nfs.functional = false
	
	
	config.vm.provider :aws do |aws, override|
		aws.user_data = File.read("aws/Setup.txt")
		aws.tags = {
		  'Name' => @aws_machine_name,
		}
		aws.access_key_id=@access_key_id
		aws.secret_access_key=@secret_access_key
		aws.keypair_name=@keypair_name
		aws.ami=@ami
		aws.region=@region
		aws.instance_type=@instance_type
		#aws.security_groups= [ @security_groups ]
	end
	
	config.vm.provision :chef_solo do |chef| 
		chef.synced_folder_type = "winrm" 
		chef.add_recipe("Control-M::touch_file")
		#chef.add_recipe("vim-windows")
	end	
end
```

Now - I face really ministerial mess.
First of all I had to create precooked base windows image at which I pre-installed chef client, since at windows vagrant function "chef_install simply do not works...

But after I did it began really strange mess. 
When I run vagrant with those job from Linux machine (Redhat) - it works.
When I run same job with same vagrant file from windows machine(that means - I installed vagrant at my windows desktop and run it with those vagratfile from there) - I get:

```ruby
==> default: Uploading with WinRM: C:/DevOps/cookbooks => C:/vagrant-chef/353b41
3e9c77f16b0448c1300d9ab1e0/cookbooks
==> default: Running provisioner: chef_solo...
==> default: Detected Chef (latest) is already installed
Generating chef JSON and uploading...
==> default: Running chef-solo...
==> default: Exception calling "Run" with "1" argument(s): "Element not found. (
Exception
==> default: from HRESULT: 0x80070490)"
==> default: At C:\tmp\vagrant-elevated-shell.ps1:61 char:1
==> default: + $registered_task.Run($null) | Out-Null
==> default: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> default:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocatio
nException
==> default:     + FullyQualifiedErrorId : ComMethodTargetInvocation
==> default:
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.*
```

I have tried it number of times. From my local desctop and from windows virtual machine that intself runs at aws... Always same result!

**Comment by sethvargo** [comment]
Hi @psimonovsk 

What version of Chef do you have installed on those windows machines? Do you have administrator privledges? Chef needs admin privledges to run on windows.

**Comment by psimonovsk** [comment]
Yes - I have admin privileges. Chef client is 12.5.1

**Comment by Zardozz** [comment]
Also having this same problem
Evironment:-
ChefDK 0.6.2
Vagrant 1.7.4
VirtualBox 5.0.6
Host OS Windows 10 64bit
Guess OS Window 8 32 bit
Tried Chef solo and Chef Zero provisioners and both the same
Chef client verion 11.14.2

Debug output below:-

```
 INFO winrm: Uploading: C:/Users/anbec/AppData/Local/Temp/vagrant-elevated-shell20151110-11316-1e42xbyps1 to c:/tmp/vagrant-elevated-shell.ps1
DEBUG winrmshell: powershell executing:
powershell -executionpolicy bypass -file "c:/tmp/vagrant-elevated-shell.ps1" -username "vagrant" -password "vagrant" -encoded_command "YwBoAGUAZgAtAGMAbABpAGUAbgB0ACAALQAtAGMAbwBuAGYAaQBnACAAQwA6AFwAdgBhAGcAcgBhAG4AdAAtAGMAaABlAGYAXABjAGwAaQBlAG4AdAAuAHIAYgAgAC0ALQBqAHMAbwBuAC0AYQB0AHQAcgBpAGIAdQB0AGUAcwAgAEMAOgBcAHYAYQBnAHIAYQBuAHQALQBjAGgAZQBmAFwAZABuAGEALgBqAHMAbwBuACAALQAtAGwAbwBjAGEAbAAtAG0AbwBkAGUAIAAtAC0AbABvAGcAXwBsAGUAdgBlAGwAIABkAGUAYgB1AGcAIAAtAC0AZgBvAHIAYwBlAC0AZgBvAHIAbQBhAHQAdABlAHIAIAAtAC0AbgBvAC0AYwBvAGwAbwByADsAIABlAHgAaQB0ACAAJABMAEEAUwBUAEUAWABJAFQAQwBPAEQARQA="
if ($?) { exit 0 } else { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }
 INFO interface: info: Exception calling "Run" with "1" argument(s): "Element not found. (Exception
 INFO interface: info: ==> win32: Exception calling "Run" with "1" argument(s): "Element not found. (Exception
==> win32: Exception calling "Run" with "1" argument(s): "Element not found. (Exception
 INFO interface: info: from HRESULT: 0x80070490)"
 INFO interface: info: ==> win32: from HRESULT: 0x80070490)"
==> win32: from HRESULT: 0x80070490)"
 INFO interface: info: At C:\tmp\vagrant-elevated-shell.ps1:61 char:1
+ $registered_task.Run($null) | Out-Null
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ComMethodTargetInvocation

 INFO interface: info: ==> win32: At C:\tmp\vagrant-elevated-shell.ps1:61 char:1
==> win32: + $registered_task.Run($null) | Out-Null
==> win32: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> win32:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
==> win32:     + FullyQualifiedErrorId : ComMethodTargetInvocation
==> win32:
==> win32: At C:\tmp\vagrant-elevated-shell.ps1:61 char:1
==> win32: + $registered_task.Run($null) | Out-Null
==> win32: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> win32:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
==> win32:     + FullyQualifiedErrorId : ComMethodTargetInvocation
==> win32:
DEBUG winrmshell: Output: {:data=>[{:stderr=>"Exception calling \"Run\" with \"1\" argument(s): \"Element not found. (Exception \r\n"}, {:stderr=>"from HRESULT: 0x80070490)\"\r\n"}, {:stderr=>"At C:\\tmp\\vagrant-elevated-shell.ps1:61 char:1\r\n+ $registered_task.Run($null) | Out-Null\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException\r\n    + FullyQualifiedErrorId : ComMethodTargetInvocation\r\n \r\n"}], :exitcode=>1}
```

The encoded commad decodes correctly and it you log on to the guest OS and run the same decode command from an elavated command prompt then Chef runs fine.
If you try and run the scheduled task the powershell created from the computer management console on the guest OS you get an error (Picture attached)
![winrm](https://cloud.githubusercontent.com/assets/13763054/11089454/beb38cf8-8861-11e5-9ba3-3b75d04179f7.PNG)
(Refreshing still show the "WinRM_Elavated_Shell" task

**Comment by sethvargo** [comment]
The next version of Vagrant will automatically install Chef on Windows for you. I just ran Chef on Windows 2012 R2 and Windows 8 without issue. I believe this has been fixed (note: I used Chef 12, not 11). All indications seem to point to this being an issue with Chef itself, not Vagrant. Vagrant is just running `chef-client`. Thanks! :smile:

**Comment by Zardozz** [comment]
I will give this a try when the install is available for the next version
Might have to wait for the migration of the cookbooks used to Chef 12 as well (as Chef 12 broke some of them)

But I'm not sure it will fix it as the chef install was good on the guest OS as manually running the encoded command that the scheduled task was set to run (which was "chef-client ....") was successful.
It was just the scheduled task vagrant had created was bad.

**Comment by visshal** [comment]
Still facing this issue.

Dev box: Mac OS X
Guest OS: Windows8
Provider: Vagrant
Provisioner: Chef_solo
Chef Development Kit Version: 0.15.16
chef-client version: 12.11.18
Vagrant: 1.8.4

Vagrant:
`config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ["cookbooks", "~/winvagrant/cookbooks"]
    chef.add_recipe "fiddler::default"
  end `

`==> default: Exception calling "Run" with "1" argument(s): "Element not found. (Exception 
==> default: from HRESULT: 0x80070490)"
==> default: At C:\tmp\vagrant-elevated-shell.ps1:73 char:1
==> default: + $registered_task.Run($null) | Out-Null
==> default: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> default:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
==> default:     + FullyQualifiedErrorId : ComMethodTargetInvocation
==> default:  
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.`

**Comment by lonniev** [comment]
I'm lovin' it. I get to experience this bug as well.

**Comment by lonniev** [comment]
My guess (knowing zilch about Powershell). The object referenced by the `registered_task` variable no longer (or never did) exist at the time it is dereferenced on line 73. That is, the exception isn't about calling the Run method with 1 argument but is about calling a method Run on a reference to either an object that doesn't exist or which doesn't have a Run method.

**Comment by lonniev** [comment]
If Run can't be called on line 73 because it is null, then GetFolder().GetTask( byName ) has failed to find a matching task. Why it can't find an expected task is another question.

Can the owner of this code make this code more robust?

```powershell
$registered_task = $folder.GetTask("\$task_name")
$registered_task.Run($null) | Out-Null
```

**Comment by lonniev** [comment]
The file that needs robustification is:

`vagrant-1.8.5/plugins/communicators/winrm/scripts/elevated_shell.ps1.erb`

**Comment by lonniev** [comment]
Just adding a Try/Catch block around the likely error area, gets us this:

```powershell
Error 'Exception calling "Run" with "1" argument(s): "Element not found. (Exception from HRESULT: 0x80070490)"' on Item ''' while attempting Schedule.Service COM methods for User *user*, Password *password*.
==> sl-tt-sync: Command line would have been: /c powershell.exe -EncodedCommand JABQA...EAEUA &gt; C:\Windows\Temp\WinRM_Elevated_Shell.log 2&gt;&amp;1
```

The same exception as before (of course, good) but the additional bit of information that the Schedule Service can't find the task WinRM_Elevated_Shell that should have been registered immediately before the Run attempt.

**Comment by lonniev** [comment]
Windows stores registered Tasks in the C:\Windows\System32\Tasks folder in their XML specifications.

One can use the schtasks.exe utility to try to run these Tasks from Powershell.

```powershell
PS C:\Windows\System32\Tasks> schtasks /Run /TN \WinRM_Elevated_Shell
ERROR: Element not found.
PS C:\Windows\System32\Tasks>
```

This is the same error that the vagrant winrm communicator encounters. The WinRM_Elevated_Shell file is in the current directory and the error is different than what one gets when the file is not present.

Either the current user lacks permissions or something is flawed in the Task file specification.

**Comment by mwrock** [comment]
can you run `schtasks.exe /query /xml /tn WinRM_Elevated_Shell` on the vagrant box and include the output xml? The `Element not found` error makes me think the xml may be malformed.

**Comment by lonniev** [comment]
This is exactly what I am working with. Sure, I can paste a sample of the
XML.

PS C:\Windows\System32\Tasks> schtasks.exe /query /xml /tn WinRM_Elevated_Shell

<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2"
xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo />
  <Triggers />
  <Principals>
    <Principal id="Author">
      <RunLevel>HighestAvailable</RunLevel>
      <UserId>SL-TT-SYNC\vagrant</UserId>
      <LogonType>Password</LogonType>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>false</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>false</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT2H</ExecutionTimeLimit>
    <Priority>4</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>cmd</Command>
      <Arguments>/c powershell.exe -EncodedCommand
JABQAHIAbwBnAHIAZQBzAHMAUAByAGUAZgBlAHIAZQBuAGMAZQA9ACcAUwBpAGwAZQBuA
HQAbAB5AEMAbwBuAHQAaQBuAHUAZQAnADsAIABjAGgAZQBmAC0AcwBvAGwAbwAgAC0ALQBjAG8AbgBmAGkAZwAgAEMAOgBcAHYAYQBnAHIAYQBuAHQALQBjA
GgAZQBmAFwAcwBvAGwAbwAuAHIAYgAgAC0ALQBqAHMAbwBuAC0AYQB0AHQAcgBpAGIAdQB0AGUAcwAgAEMAOgBcAHYAYQBnAHIAYQBuAHQALQBjAGgAZQBmA
FwAZABuAGEALgBqAHMAbwBuACAALQAtAGwAbwBnAF8AbABlAHYAZQBsACAAdwBhAHIAbgAgAC0ALQBmAG8AcgBjAGUALQBmAG8AcgBtAGEAdAB0AGUAcgA7A
CAAZQB4AGkAdAAgACQATABBAFMAVABFAFgASQBUAEMATwBEAEUA &gt;
C:\Windows\Temp\WinRM_Elevated_Shell.log 2&gt;&amp;1</Arguments
>
    </Exec>
  </Actions>

The argument string is the encoded script to run the chef-solo client and
it decodes and runs fine.

I’d like to see either valid time and user info in the RegistrationInfo
element or not have it there at all. Likewise for the Triggers element.
Otherwise, it looks very similar to simple sample Task XMLs for tasks that
do register and run with the schtasks app.



-- 
Lonnie VanZandt
303-900-3048

On 23 September 2016 at 22:15:50, Matt Wrock (notifications@github.com)
wrote:

can you run schtasks.exe /query /xml /tn WinRM_Elevated_Shell on the
vagrant box and include the output xml? The Element not found error makes
me think the xml may be malformed.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/mitchellh/vagrant/issues/6418#issuecomment-249344027>,
or mute the thread

**Comment by lonniev** [comment]
Hmm, I wonder if this empty RegistrationInfo element is a clue.

**Comment by lonniev** [comment]
No such luck.

If I set task.RegistrationInfo prior to the RegisterTaskDefinition call then the queried XML has that registration info in it -- but the Element Not Found error still occurs.

**Comment by lonniev** [comment]
xmllint claims it is parseable XML so I'm not overlooking some missing closing bracket or something trivially wrong like that.

**Comment by lonniev** [comment]
When I change the Principals>Principal>LogonType to InteractiveToken from Password, then when run from a Powershell command shell as the indicated Principal, the command:

`schtasks.exe /run /tn WinRM_Elevated_Shell`

launches a separate cmd.exe window and the requested powershell script executes to completion.

This highly suggests that there is some authentication issue with the current vagrant user and its ability to run non-interactive tasks.

**Comment by mwrock** [comment]
Is the user in the administrators group?

**Comment by lonniev** [comment]
Yes, the user is “vagrant” and for over a year vagrant has been a properly configured Administrator and WinRM user.



-- 
Lonnie VanZandt
303-900-3048

On 24 September 2016 at 11:46:04, Matt Wrock (notifications@github.com) wrote:

Is the user in the administrators group?

**Comment by lonniev** [comment]
Apparently, there is something wrong with the Action Exec Arguments. Using the Task Scheduler GUI to rapidly try alternatives (versus hacking up XML fragments over and over), if I replace the Arguments with just "/c powershell.exe", then the WinRM_Elevated_Shell becomes runnable. It sits in a Running state doing nothing. There is no Element Not Found error.

I can paste back the argument string with the Encoded script and with the I/O redirection at the tail end and ... oddly ... the Task remains runnable and can be stopped and restarted.

Perhaps there is some spurious character in the XML that arrives from the template file or perhaps the I/O redirection is blocked by some temp file with the wrong permissions. I'm not sure yet why removing the Arguments element and then adding what appears to be the same content back would make a difference.

**Comment by lonniev** [comment]
It could be, instead, that as the Task Scheduler GUI asks for the runtime user password, it properly saves within the Task definition the right credentials. This happens at the conclusion of the change for editing the Arguments.

It does not make sense that simply cutting out and then pasting back the Argument string would make a difference.

**Comment by lonniev** [comment]
It is not just the act of opening, modifying, and saving the task in the Task Scheduler GUI that makes the Task runnable. I have to modify the Arguments element to make the task runnable (even if just cutting, saving, running, stopping, editing, pasting, saving, and running).

If I make a small reversible change on one of the other properties, the Task does not become runnable. Something is important about how the Argument element is resaved.

**Comment by lonniev** [comment]
I found a workaround. I rewrote elevated_shell.ps1.erb to eliminate the wordy, errorprone, and brittle XML approach with direct setting of the TaskDefinition object.

The gist is here: [https://gist.github.com/lonniev/dbf81bfddce0c9e7fc9c57d7896447bd](https://gist.github.com/lonniev/dbf81bfddce0c9e7fc9c57d7896447bd)

This allows me to focus on the individual settings without having to worry about keeping strings consistent with XML and wondering if the entire string actually conforms to Microsoft's latest schema for Task Definitions.

I suspected that the Action.Arguments string with the call to powershell was causing a problem.

What I currently suspect now is that the Task Scheduler was refusing to start a new instance of the WinRM_Elevated_Shell because the `MultipleInstancesPolicy` setting was specifying that new instances of the Task are not be ignored if a prior instance is still running. I changed the policy to TaskInstancesStopExisting and the latest requests now run.

I also force the LogonType settings to TASK_LOGON_INTERACTIVE_TOKEN_OR_PASSWORD for both the TaskDefinition and for the TaskRegistration. This allows a Task that demands an interactive session to run.

Getting rid of the XML string means the template processing is all unnecessary because now the variability in the script is all handled with powershell variables and powershell processing.

One other change was to open the $out_file in $env:TEMP/WinRM_Elevated_Shell.log instead of in $env:/SystemRoot/TEMP/WinRM_Elevated_Shell.log.

A particular machine might not have a folder named "TEMP" under its system root folder. It is expected to have a %TEMP% environment variable that indicates where temp files go.

**Comment by mwrock** [comment]
Interesting.  I really wish I could reproduce this on my end. I have been using local vagrant boxes and vagrant-omnibus without issue.

We edit the task xml because its the best way to create tasks in a way that allow you to adjust such settings as `priority`, `DisallowStartIfOnBatteries`, etc on current and older windows os versions.

I'm glad you found a work around but would love to truly understand the "Element Not Found" error. I'm really not so certain it is related to malformed XML. While the `MultipleInstancesPolicy` issue is certainly noteworthy. Vagrant typically executes the commands synchronously which would prevent multiple instances.

One thing worth checking is the system event log. I've done a bit of research and there are some occurences of the "Element not found" error that will provide more details in that event log.

**Comment by lonniev** [comment]
I do not believe the XML was malformed. The reason I jettisoned the XML is that it is a brittle software tactic. In the source code, it is merely a collection of characters and there is no easy way to assure that it remains syntactically and schematically valid. XML also has low expressibility: it takes at least 2x the number of characters to access and alter properties as does an object property getter/setter tactic. The use of the ScriptingObjects allows us to get immediate feedback at powershell execution time (not at later Task execution time) that a specific object or property is being misused or type abused.

We may also gain a little performance boost by not having to push around a moderate-sized XML string in addition to the ScriptingObject instances.

Apparently, what really was happening is rejection of the run request because a prior instance of the Task is running or was left in the Task Scheduler in a non-idle state. (Must we explicitly set the Task state to idle when registering it if no Trigger is supplied? I don’t know.)

That is, I think it is the change of the Multiple Instance Policy from TASK_INSTANCE_IGNORE_NEW to TASK_INSTANCES_STOP_EXISTING. This shifts from protecting prior instances to preferring new instances. (This would the wrong thing to do if chef is parallelizing priority requests but I believe it does not support that.)

Clearly, the need for WinRM to have to do anything like this is unfortunate and the whole area is a smelly, ripe area for improvement.



-- 
Lonnie VanZandt
303-900-3048

On 25 September 2016 at 07:21:21, Matt Wrock (notifications@github.com) wrote:

Interesting. I really wish I could reproduce this on my end. I have been using local vagrant boxes and vagrant-omnibus without issue.

We edit the task xml because its the best way to create tasks in a way that allow you to adjust such settings as priority, DisallowStartIfOnBatteries, etc on current and older windows os versions.

I'm glad you found a work around but would love to truly understand the "Element Not Found" error. I'm really not so certain it is related to malformed XML. While the MultipleInstancesPolicy issue is certainly noteworthy. Vagrant typically executes the commands synchronously which would prevent multiple instances.

One thing worth checking is the system event log. I've done a bit of research and there are some occurences of the "Element not found" error that will provide more details in that event log.

**Comment by mwrock** [comment]
Heh, definitely don't have to convince me of the horribleness of XML. :) We had not looked at the COM approach but that would work. It works accross all the OS versions we care about. If you wanted to contribute this (no pressure at all) we have moved this elevated logic to the winrm-elevated gem. I plan to to refactor the winrm vagrant communicator to use that in a few weeks.

**Comment by lonniev** [comment]
I’m fine with it getting merged in wherever appropriate. I only know that it works for my particular situation. The challenge with vagrant is that it has to be tested to work across hundreds of permutations. I don’t have the means to test that way.



-- 
Lonnie VanZandt
303-900-3048

On 25 September 2016 at 16:08:24, Matt Wrock (notifications@github.com) wrote:

Heh, definitely don't have to convince me of the horribleness of XML. :) We had not looked at the COM approach but that would work. It works accross all the OS versions we care about. If you wanted to contribute this (no pressure at all) we have moved this elevated logic to the winrm-elevated gem. I plan to to refactor the winrm vagrant communicator to use that in a few weeks.

**Comment by lonniev** [comment]
FYI: MaxShellsPerUser for Windows 2012 is merely 30. That’s 6 times the limit for Windows 2008 yet it still isn’t enough for Vagrant/Chef.

I manually provision Set-Item WSMAN:\localhost\Shell\MaxShellsPerUser -Value 0 to get free of this constraint.

That is, in addition to the edits to the elevated script template, a proper fix also includes relaxing the MaxShells limit.



-- 
Lonnie VanZandt
303-900-3048

On 25 September 2016 at 16:45:10, Lonnie VanZandt (lonniev@gmail.com) wrote:

I’m fine with it getting merged in wherever appropriate. I only know that it works for my particular situation. The challenge with vagrant is that it has to be tested to work across hundreds of permutations. I don’t have the means to test that way.



-- 
Lonnie VanZandt
303-900-3048

On 25 September 2016 at 16:08:24, Matt Wrock (notifications@github.com) wrote:

Heh, definitely don't have to convince me of the horribleness of XML. :) We had not looked at the COM approach but that would work. It works accross all the OS versions we care about. If you wanted to contribute this (no pressure at all) we have moved this elevated logic to the winrm-elevated gem. I plan to to refactor the winrm vagrant communicator to use that in a few weeks.
