### ISSUE TITLE
Vagrant 1.8.0 - "One of the parameters was invalid" for vmrun command after vagrant up

### ISSUE THREAD

**Issue by geerlingguy** [mitchellh/vagrant#6698]
I'm running VMware Fusion 8.1.0 and Vagrant 1.8.0, and the license and plugin for Vagrant are installed correctly. Since upgrading to 1.8.0, I've been getting the following message when I try to build a new VM:

```
An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:

Command: ["clone", "/Users/jeff.geerlingguy/.vagrant.d/boxes/geerlingguy-VAGRANTSLASH-ubuntu1204/1.0.8/vmware_desktop/packer-ubuntu-12.04-amd64.vmx", "/path/to/box/configuration/.vagrant/machines/vagrantboxname/vmware_fusion/b3dd383b-60f4-49cf-8db4-815db2cb113a/packer-ubuntu-12.04-amd64.vmx", "linked", {:notify=>[:stdout, :stderr]}]

Stdout: Error: One of the parameters was invalid
```

This occurs when running `vagrant up`.

I tried removing all boxes present on the system with `vagrant box remove` as well. It seems VMware Fusion isn't happy with the linking/cloning command being used by Vagrant.

**Comment by geerlingguy** [comment]
So... apparently 'linked cloning' (which seems a rather basic feature to me) is not actually supported by Fusion 8, only by Fusion 8 Pro, which would be an additional upgrade on top of Fusion 8.

At this point, I'm a couple hundred bucks down the VMware rabbit hole, and I'm willing to go a little further... but I double-checked the license purchase page (https://www.vagrantup.com/vmware) and it says "Fusion 8" without mentioning Pro.

Is there a way you could either automatically detect in Vagrant if Pro or 'normal' is installed, and if 'normal' then don't add 'linked' so the `vmrun clone` command works still? Otherwise, please update the license purchase page/documentation to explicitly state that VMware _Pro_ is required to use the Vagrant plugin.

**Comment by geerlingguy** [comment]
For now, I'm going to stick with `vagrant up --provider=virtualbox`, but I'd like to know if I should plan on getting Fusion 8 Pro (hopefully VMware will be kind and not make me double-pay the upgrade, since I just paid for the Fusion 8 upgrade), or if the plugin will be made to work with regular Fusion 8.

**Comment by mitchellh** [comment]
We're going to fix this by auto-detecting if it is avilable! Sorry.

**Comment by mitchellh** [comment]
![2015-12-21 at 2 56 pm](https://cloud.githubusercontent.com/assets/1299/11943471/fb91984e-a7f2-11e5-9bfc-44838ad4db90.png)

Incoming into the next point release today (of vagrant-vmware).

**Comment by geerlingguy** [comment]
@mitchellh - Thanks for the quick work!

**Comment by mitchellh** [comment]
Fixed, v4.0.4 of the plugin is out now

**Comment by stephenhowells** [comment]
With Vagrant 1.8.0, VMWare Plugin 4.0.4, and VMWare Fusion 8.1.0 I'm still getting this:

```
Bringing machine 'default' up with 'vmware_fusion' provider...
==> default: Cloning VMware VM: 'laravel/homestead'. This can take some time...
An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:

Command: ["clone", "/Users/Stephen/.vagrant.d/boxes/laravel-VAGRANTSLASH-homestead/0.4.0/vmware_desktop/ubuntu-14.04-amd64.vmx", "/Users/Stephen/Homestead/.vagrant/machines/default/vmware_fusion/527c867d-ce93-498a-8d1c-f6aad0f4764b/ubuntu-14.04-amd64.vmx", "linked", {:notify=>[:stdout, :stderr]}]

Stdout: Error: One of the parameters was invalid

Stderr:
```

**Comment by stephenhowells** [comment]
I should add I ensured that the license was installed. This occurs for me when I try `vagrant up` on a newly downloaded box. ¯\\\_(ツ)_/¯

**Comment by mitchellh** [comment]
Hah, 4.0.4 checks stderr. Sorry, I couldn't find a non-pro license to test on. I'll update that ASAP. 4.0.5 will be what you want shortly.

**Comment by geerlingguy** [comment]
It's working for me now. Thanks!

**Comment by fhenri** [comment]
I had the exact same issue and now its working for me - I had vagrant-vmware-fusion (4.0.3) installed (with vagrant 1.8.1 and vmware 8); for some reasons `vagrant plugin update` did not make the upgrade but after uninstall and reinstalling vagrant-vmware-fusion now on 4.0.6, everything is fine
