### ISSUE TITLE
"No host IP was given to the Vagrant core NFS helper." with Hyper-V

### ISSUE THREAD

**Issue by Mathyn** [mitchellh/vagrant#7816]
I am trying to get Vagrant to work with Hyper-V. I run into the following error

```
No host IP was given to the Vagrant core NFS helper. This is
an internal error that should be reported as a bug.
```

I am using Vagrant 1.8.5 with Hyper-V installed on Windows 10 (with the latest big update).

The guest operating system is Ubuntu 14.04 (ericmann/trusty64).

My Vagrant file looks like this:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['INSTALL_CUSTOMER'] ||= "true"
ENV['START_CUSTOMER'] ||= "true"

Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = "ericmann/trusty64"

   config.vm.network "forwarded_port", guest: 80, host: 80
   config.vm.network "forwarded_port", guest: 35729, host: 35729
   config.vm.network "forwarded_port", guest: 27017, host: 27017

   config.vm.synced_folder "./", "/home/vagrant/xxxx", type: "smb"

   config.vm.provider "hyperv" do |hv|
     hv.cpus = 2
     hv.memory = 2048
   end

   config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     # vb.gui = true

     # Customize the amount of memory on the VM:
     vb.memory = "2048"
     vb.cpus = 2

     vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
   end

   config.vm.provision "shell", 
    path: "provisioning.sh", 
    privileged: false, 
    keep_color: true,
    args: [ENV['INSTALL_CUSTOMER'], ENV['START_CUSTOMER']]

   config.trigger.after :up do
    system("
      echo 'Starting debug tunnels:'
      ./debug-tunnels.sh
    ")
   end
end
```

During the `vagrant up` command I see the following output:

```
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Configured startup memory is 2048
==> default: Configured cpus number is 2
==> default: Importing a Hyper-V instance
    default: Cloning virtual hard drive...
    default: Creating and registering the VM...
    default: Successfully imported a VM with name: Trusty Tahr
==> default: Starting the machine...
==> default: Waiting for the machine to report its IP address...
    default: Timeout: 120 seconds
    default: IP: 192.168.137.71
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 192.168.137.71:22
    default: SSH username: vagrant
    default: SSH auth method: password
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Preparing SMB shared folders...
    default: You will be asked for the username and password to use for the SMB
    default: folders shortly. Please use the proper username/password of your
    default: Windows account.
    default:
    default: Username: xxxxxxxx
    default: Password (will be hidden):
==> default: Mounting SMB shared folders...
    default: D:/xxxx/BackEnd => /home/vagrant/xxxxx
No host IP was given to the Vagrant core NFS helper. This is
an internal error that should be reported as a bug.
```

I do not understand this error message. I am not using NFS but SMB. Anyone know what I am doing wrong?

**Comment by andyp1per** [comment]
You are doing nothing wrong - it's a bug in Vagrant

**Comment by chrisroberts** [comment]
Fixed by #8819

**Comment by frutality** [comment]
Is this fixed in 2.0?

I am asking because I have similar configuration and same error. I updated Vagrant to 2.0, updated plugins, but error still here. 

I was pretty happy with Virtualbox provider, but decided: time has come to learn Docker. Which needs Hyper-V. Which is incompatible with Virtualbox. But I have bunch projects at my dev-machine using vagrant, I need them to work too.

**Comment by edhardie** [comment]
I'm still seeing this error in 2.0.0 so guessing it's not made its way into a release yet.

**Comment by dwickern** [comment]
@chrisroberts #8819 only changed the virtualbox provider so I don't see how that would fix this hyper-v issue

**Comment by meotimdihia** [comment]
2.01 still seeing this error. Hyper V and sharing folder vie SMB.

**Comment by Herschdorfer** [comment]
how is that closed? problem still exist ins hyperv provider.

**Comment by TheDeadCode** [comment]
Rly need this on Hyper-V :(
