### ISSUE TITLE
Unable to restart Vagrant boxes due to port collision

### ISSUE THREAD

**Issue by elimentz** [mitchellh/vagrant#8489]
Since this morning, I can't boot up any of my VMs anymore due to the error below:

```
MacBook-Pro:htdocs user$ vagrant up
Bringing machine 'vm-dev' up with 'vmware_fusion' provider...
==> vm-dev: Checking if box 'puphpet/ubuntu1604-x64' is up to date...
==> vm-dev: Verifying vmnet devices are healthy...
==> vm-dev: Preparing network adapters...
Some of the defined forwarded ports would collide with existing
forwarded ports on VMware network devices. This can be due to
existing Vagrant-managed VMware machines, or due to manually
configured port forwarding with VMware. Please fix the following
port collisions and try again:

2222
```

I've had this issue for weeks now, but so far I was able to work around it by restarting my terminal but now nothing works. I tried everything:

- I restarted my terminal
- I reinstalled vmware
- I reinstalled vagrant
- I rebooted my machine (several times)

Any help is greatly appreciated...

- VMware fusion pro 8.5.6
- Vagrant 1.9.3
- Vagrant vmware fusion plugin 4.0.18

**Comment by chrisroberts** [comment]
Hi there. Please clear out any entries defined in the `[incomingtcp]` section of the `nat.conf` file located at: `/Library/Preferences/VMware Fusion/vmnet8/nat.conf`. That should resolve the collision issues.

I'm going to close this issue, but if the collisions continue to occur, please reopen this issue. Cheers!

**Comment by elimentz** [comment]
@chrisroberts Thanks, that did indeed solve my issue. I still get a port collision notification but the issue fixed while booting the box.

does this mean I'm gonna have to do this every time I open and/or close a vagrant box? Because this will get annoying very, ***very*** quickly...

**Comment by chrisroberts** [comment]
@elimentz No, it should not keep occurring. There is an issue where Vagrant entry marks can get scrubbed from the configuration file when the service is restarted. Newer versions of the plugin include port forward logging to automatically repair the file if the markers are lost. There is some more information here: https://github.com/mitchellh/vagrant/issues/7948#issuecomment-283108576 If you run into this issue again, please do open a new ticket. Cheers!

**Comment by elimentz** [comment]
@chrisroberts I sure as hell hope so, thanks for the effort. But I will point out that I was already on version 4.0.18 of the vagrant plugin when this issue occurred...

But ok, fingers crossed :-)

**Comment by jakewan** [comment]
I'm having this issue too, only when I clear out the entries under [incomingtcp], something keeps putting them back as soon as I start the VM again.  Consequently, I can't even start the VM without this message:

> Some of the defined forwarded ports would collide with existing
> forwarded ports on VMware network devices. This can be due to
> existing Vagrant-managed VMware machines, or due to manually
> configured port forwarding with VMware. Please fix the following
> port collisions and try again:
> 
> 2222, 8080

It _feels_ like the VMWare plugin is keeping a cache of what it thinks the nat.conf entries should be and uses them to overwrite my edits before actually setting up the VM.

In addition to clearing the entries under [incomingtcp], I've tried deleting both /Library/Preferences/VMware Fusion/vmnet8/nat.conf.bak and my project's .vagrant/ directory, hoping this would somehow clear that hypothetical cache, but to no avail.

I'm running:

- Vagrant 1.9.4
- vagrant-vmware-fusion 4.0.19
- VMWare Fusion 8.5.6

**Comment by irperera** [comment]
the nat.conf file is locked, how can i unlock it?
