### ISSUE TITLE
vagrant plugin install: timed out (https://gems.hashicorp.com/specs.4.8.gz)

### ISSUE THREAD

**Issue by dominikzogg** [mitchellh/vagrant#8795]
### Vagrant version
Vagrant 1.9.7

### Host operating system
Ubuntu 16.04 with PPA kernel (4.11, 4.12)

### Expected behavior
vagrant plugin install vagrant-hostmanager should install the plugin

### Actual behavior
No plugin that i tried to install was installable. I've updated from 1.8.7, but then i purged the installation and deleted the ~/.vagrant.d.,  which does not help

```
vagrant plugin install vagrant-hostmanager
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

  timed out (https://gems.hashicorp.com/specs.4.8.gz)

Source: https://gems.hashicorp.com/
```

```
$ vagrant plugin update
Updating installed plugins...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Unable to resolve dependency: user requested 'vagrant-share (> 0)'
```

### Steps to reproduce
1. install vagrant
2. install any vagrant plugin

**Comment by briancain** [comment]
Hey @dominikzogg - are you able to ping `gems.hashicorp.com` and get a response? Are you behind a proxy that might prevent you from reaching the gems mirror? Also can you provide a debug log when attempting to install the plugin? (i.e. `vagrant plugin install vagrant-hostmanager --debug`). Thanks!

**Comment by florianb** [comment]
I am having the same issue.

### Ping

```
➜ ping gems.hashicorp.com
PING d3bqwsh65659ed.cloudfront.net (52.222.162.126): 56 data bytes
64 bytes from 52.222.162.126: icmp_seq=0 ttl=243 time=35.468 ms
64 bytes from 52.222.162.126: icmp_seq=1 ttl=243 time=26.024 ms
64 bytes from 52.222.162.126: icmp_seq=2 ttl=243 time=27.777 ms
64 bytes from 52.222.162.126: icmp_seq=3 ttl=243 time=32.228 ms
^C
--- d3bqwsh65659ed.cloudfront.net ping statistics ---
4 packets transmitted, 4 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 26.024/30.374/35.468/3.710 ms
```

### `vagrant plugin install vagrant-vbguest --debug`
```
➜ vagrant plugin install vagrant-vbguest --debug
 INFO global: Vagrant version: 1.9.7
 INFO global: Ruby version: 2.3.4
 INFO global: RubyGems version: 2.5.2
 INFO global: VAGRANT_OLD_ENV_TERM_PROGRAM_VERSION="3.0.15"
 INFO global: VAGRANT_OLD_ENV_ITERM_SESSION_ID="w0t1p0:CD066784-5408-4597-8B61-5D79E477EDAC"
 INFO global: VAGRANT_OLD_ENV_PAGER="less"
 INFO global: VAGRANT_OLD_ENV_TERM="xterm-256color"
 INFO global: VAGRANT_OLD_ENV_HOME="/Users/<<USERNAME>>"
 INFO global: VAGRANT_OLD_ENV_LS_COLORS="no=00:fi=00:di=01;34:ln=00;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=41;33;01:ex=00;32:ow=0;41:*.cmd=00;32:*.exe=01;32:*.com=01;32:*.bat=01;32:*.btm=01;32:*.dll=01;32:*.tar=00;31:*.tbz=00;31:*.tgz=00;31:*.rpm=00;31:*.deb=00;31:*.arj=00;31:*.taz=00;31:*.lzh=00;31:*.lzma=00;31:*.zip=00;31:*.zoo=00;31:*.z=00;31:*.Z=00;31:*.gz=00;31:*.bz2=00;31:*.tb2=00;31:*.tz2=00;31:*.tbz2=00;31:*.avi=01;35:*.bmp=01;35:*.fli=01;35:*.gif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mng=01;35:*.mov=01;35:*.mpg=01;35:*.pcx=01;35:*.pbm=01;35:*.pgm=01;35:*.png=01;35:*.ppm=01;35:*.tga=01;35:*.tif=01;35:*.xbm=01;35:*.xpm=01;35:*.dl=01;35:*.gl=01;35:*.wmv=01;35:*.aiff=00;32:*.au=00;32:*.mid=00;32:*.mp3=00;32:*.ogg=00;32:*.voc=00;32:*.wav=00;32:*.patch=00;34:*.o=00;32:*.so=01;35:*.ko=01;31:*.la=00;33"
 INFO global: VAGRANT_OLD_ENV_NVM_DIR="/Users/<<USERNAME>>/.nvm"
 INFO global: VAGRANT_OLD_ENV_NVM_BIN="/Users/<<USERNAME>>/.nvm/versions/node/v8.1.4/bin"
 INFO global: VAGRANT_OLD_ENV_TERM_SESSION_ID="w0t1p0:CD066784-5408-4597-8B61-5D79E477EDAC"
 INFO global: VAGRANT_INSTALLER_VERSION="2"
 INFO global: VAGRANT_OLD_ENV_DISPLAY="/private/tmp/com.apple.launchd.qDXYgKqWiF/org.macosforge.xquartz:0"
 INFO global: VAGRANT_OLD_ENV_GOPATH="/Users/<<USERNAME>>/go"
 INFO global: VAGRANT_OLD_ENV_TERM_PROGRAM="iTerm.app"
 INFO global: VAGRANT_OLD_ENV_NVM_IOJS_ORG_MIRROR="https://iojs.org/dist"
 INFO global: VAGRANT_OLD_ENV_NVM_PATH="/Users/<<USERNAME>>/.nvm/versions/node/v8.1.4/lib/node"
 INFO global: VAGRANT_OLD_ENV_ZSH="/Users/<<USERNAME>>/.oh-my-zsh"
 INFO global: VAGRANT_INSTALLER_EMBEDDED_DIR="/opt/vagrant/embedded"
 INFO global: VAGRANT_OLD_ENV_SECURITYSESSIONID="186a6"
 INFO global: VAGRANT_OLD_ENV_USER="<<USERNAME>>"
 INFO global: VAGRANT_OLD_ENV_LC_CTYPE="de_DE.UTF-8"
 INFO global: VAGRANT_OLD_ENV_NVM_CD_FLAGS="-q"
 INFO global: VAGRANT_OLD_ENV_COLORFGBG="15;0"
 INFO global: VAGRANT_OLD_ENV_LANG="de_DE.UTF-8"
 INFO global: VAGRANT_OLD_ENV_PWD="/Users/<<USERNAME>>/<<WORKING_DIRECTORY>>"
 INFO global: VAGRANT_OLD_ENV_XPC_SERVICE_NAME="0"
 INFO global: VAGRANT_OLD_ENV_NVM_NODEJS_ORG_MIRROR="https://nodejs.org/dist"
 INFO global: VAGRANT_OLD_ENV_ITERM_PROFILE="Default"
 INFO global: VAGRANT_OLD_ENV_XPC_FLAGS="0x0"
 INFO global: VAGRANT_OLD_ENV_COMMAND_MODE="unix2003"
 INFO global: VAGRANT_OLD_ENV_MANPATH="/Users/<<USERNAME>>/.nvm/versions/node/v8.1.4/share/man:/usr/local/share/man/de:/usr/local/share/man:/usr/share/man:/Applications/Xcode.app/Contents/Developer/usr/share/man:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man"
 INFO global: VAGRANT_OLD_ENV_SHELL="/bin/zsh"
 INFO global: VAGRANT_OLD_ENV___CF_USER_TEXT_ENCODING="0x1F5:0x0:0x3"
 INFO global: VAGRANT_OLD_ENV_LESS="-R"
 INFO global: VAGRANT_OLD_ENV_TMPDIR="/var/folders/bj/h379n0p16zq_gnzqhj7tq06c0000gn/T/"
 INFO global: VAGRANT_OLD_ENV__="/usr/local/bin/vagrant"
 INFO global: VAGRANT_INSTALLER_ENV="1"
 INFO global: VAGRANT_OLD_ENV_SSH_AUTH_SOCK="/private/tmp/com.apple.launchd.wmJrI9cVDE/Listeners"
 INFO global: VAGRANT_OLD_ENV_LOGNAME="<<USERNAME>>"
 INFO global: VAGRANT_OLD_ENV_SHLVL="1"
 INFO global: VAGRANT_EXECUTABLE="/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/bin/vagrant"
 INFO global: VAGRANT_OLD_ENV_Apple_PubSub_Socket_Render="/private/tmp/com.apple.launchd.QVCWYblJU0/Render"
 INFO global: VAGRANT_OLD_ENV_PATH="/Users/<<USERNAME>>/.nvm/versions/node/v8.1.4/bin:/Users/<<USERNAME>>/.rbenv/shims:/usr/local/texlive/2016/bin/x86_64-darwin:/Applications/VMware Fusion.app/Contents/Library:/Users/<<USERNAME>>/.cargo/bin:/Users/<<USERNAME>>/.cabal/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
 INFO global: VAGRANT_OLD_ENV_OLDPWD="/Users/<<USERNAME>>/<<WORKING_DIRECTORY>>"
 INFO global: VAGRANT_OLD_ENV_LSCOLORS="Gxfxcxdxbxegedabagacab"
 INFO global: VAGRANT_OLD_ENV_RBENV_SHELL="zsh"
 INFO global: VAGRANT_NO_PLUGINS="1"
 INFO global: VAGRANT_DISABLE_PLUGIN_INIT="1"
 INFO global: VAGRANT_LOG="debug"
 INFO global: Plugins:
 INFO global:   - vagrant-share = [installed: undefined constraint: > 0]
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/box/plugin.rb
 INFO manager: Registered plugin: box command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/cap/plugin.rb
 INFO manager: Registered plugin: cap command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/destroy/plugin.rb
 INFO manager: Registered plugin: destroy command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/global-status/plugin.rb
 INFO manager: Registered plugin: global-status command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/halt/plugin.rb
 INFO manager: Registered plugin: halt command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/help/plugin.rb
 INFO manager: Registered plugin: help command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/init/plugin.rb
 INFO manager: Registered plugin: init command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/list-commands/plugin.rb
 INFO manager: Registered plugin: list-commands command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/login/plugin.rb
 INFO manager: Registered plugin: vagrant-login
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/package/plugin.rb
 INFO manager: Registered plugin: package command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/plugin/plugin.rb
 INFO manager: Registered plugin: plugin command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/port/plugin.rb
 INFO manager: Registered plugin: port command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/powershell/plugin.rb
 INFO manager: Registered plugin: powershell command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/provider/plugin.rb
 INFO manager: Registered plugin: provider command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/provision/plugin.rb
 INFO manager: Registered plugin: provision command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/push/plugin.rb
 INFO manager: Registered plugin: push command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/rdp/plugin.rb
 INFO manager: Registered plugin: rdp command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/reload/plugin.rb
 INFO manager: Registered plugin: reload command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/resume/plugin.rb
 INFO manager: Registered plugin: resume command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/snapshot/plugin.rb
 INFO manager: Registered plugin: snapshot command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/ssh/plugin.rb
 INFO manager: Registered plugin: ssh command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/ssh_config/plugin.rb
 INFO manager: Registered plugin: ssh-config command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/status/plugin.rb
 INFO manager: Registered plugin: status command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/suspend/plugin.rb
 INFO manager: Registered plugin: suspend command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/up/plugin.rb
 INFO manager: Registered plugin: up command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/validate/plugin.rb
 INFO manager: Registered plugin: validate command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/version/plugin.rb
 INFO manager: Registered plugin: version command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/communicators/ssh/plugin.rb
 INFO manager: Registered plugin: ssh communicator
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/communicators/winrm/plugin.rb
 INFO manager: Registered plugin: winrm communicator
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/communicators/winssh/plugin.rb
 INFO manager: Registered plugin: windows ssh communicator
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/amazon/plugin.rb
 INFO manager: Registered plugin: Amazon Linux guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/arch/plugin.rb
 INFO manager: Registered plugin: Arch guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/atomic/plugin.rb
 INFO manager: Registered plugin: Atomic Host guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/bsd/plugin.rb
 INFO manager: Registered plugin: BSD-based guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/coreos/plugin.rb
 INFO manager: Registered plugin: CoreOS guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/darwin/plugin.rb
 INFO manager: Registered plugin: Darwin guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/debian/plugin.rb
 INFO manager: Registered plugin: Debian guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/dragonflybsd/plugin.rb
 INFO manager: Registered plugin: DragonFly BSD guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/elementary/plugin.rb
 INFO manager: Registered plugin: Elementary guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/esxi/plugin.rb
 INFO manager: Registered plugin: ESXi guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/fedora/plugin.rb
 INFO manager: Registered plugin: Fedora guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/freebsd/plugin.rb
 INFO manager: Registered plugin: FreeBSD guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/funtoo/plugin.rb
 INFO manager: Registered plugin: Funtoo guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/gentoo/plugin.rb
 INFO manager: Registered plugin: Gentoo guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/kali/plugin.rb
 INFO manager: Registered plugin: Kali guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/linux/plugin.rb
 INFO manager: Registered plugin: Linux guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/mint/plugin.rb
 INFO manager: Registered plugin: Mint guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/netbsd/plugin.rb
 INFO manager: Registered plugin: NetBSD guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/nixos/plugin.rb
 INFO manager: Registered plugin: NixOS guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/omnios/plugin.rb
 INFO manager: Registered plugin: OmniOS guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/openbsd/plugin.rb
 INFO manager: Registered plugin: OpenBSD guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/photon/plugin.rb
 INFO manager: Registered plugin: VMware Photon guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/pld/plugin.rb
 INFO manager: Registered plugin: PLD Linux guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/redhat/plugin.rb
 INFO manager: Registered plugin: Red Hat Enterprise Linux guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/slackware/plugin.rb
 INFO manager: Registered plugin: Slackware guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/smartos/plugin.rb
 INFO manager: Registered plugin: SmartOS guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/solaris/plugin.rb
 INFO manager: Registered plugin: Solaris guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/solaris11/plugin.rb
 INFO manager: Registered plugin: Solaris 11 guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/suse/plugin.rb
 INFO manager: Registered plugin: SUSE guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/tinycore/plugin.rb
 INFO manager: Registered plugin: TinyCore Linux guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/trisquel/plugin.rb
 INFO manager: Registered plugin: Trisquel guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/ubuntu/plugin.rb
 INFO manager: Registered plugin: Ubuntu guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/windows/plugin.rb
 INFO manager: Registered plugin: Windows guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/hosts/arch/plugin.rb
 INFO manager: Registered plugin: Arch host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/hosts/bsd/plugin.rb
 INFO manager: Registered plugin: BSD host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/hosts/darwin/plugin.rb
 INFO manager: Registered plugin: Mac OS X host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/hosts/freebsd/plugin.rb
 INFO manager: Registered plugin: FreeBSD host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/hosts/gentoo/plugin.rb
 INFO manager: Registered plugin: Gentoo host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/hosts/linux/plugin.rb
 INFO manager: Registered plugin: Linux host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/hosts/null/plugin.rb
 INFO manager: Registered plugin: null host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/hosts/redhat/plugin.rb
 INFO manager: Registered plugin: Red Hat Enterprise Linux host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/hosts/slackware/plugin.rb
 INFO manager: Registered plugin: Slackware host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/hosts/suse/plugin.rb
 INFO manager: Registered plugin: SUSE host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/hosts/windows/plugin.rb
 INFO manager: Registered plugin: Windows host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/kernel_v1/plugin.rb
 INFO manager: Registered plugin: kernel
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/kernel_v2/plugin.rb
 INFO manager: Registered plugin: kernel
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/providers/docker/plugin.rb
 INFO manager: Registered plugin: docker-provider
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/providers/hyperv/plugin.rb
 INFO manager: Registered plugin: Hyper-V provider
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/providers/virtualbox/plugin.rb
 INFO manager: Registered plugin: VirtualBox provider
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/provisioners/ansible/plugin.rb
 INFO manager: Registered plugin: ansible
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/provisioners/cfengine/plugin.rb
 INFO manager: Registered plugin: CFEngine Provisioner
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/provisioners/chef/plugin.rb
 INFO manager: Registered plugin: chef
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/provisioners/docker/plugin.rb
 INFO manager: Registered plugin: docker
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/provisioners/file/plugin.rb
 INFO manager: Registered plugin: file
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/provisioners/puppet/plugin.rb
 INFO manager: Registered plugin: puppet
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/provisioners/salt/plugin.rb
 INFO manager: Registered plugin: salt
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/provisioners/shell/plugin.rb
 INFO manager: Registered plugin: shell
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/pushes/atlas/plugin.rb
 INFO manager: Registered plugin: atlas
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/pushes/ftp/plugin.rb
 INFO manager: Registered plugin: ftp
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/pushes/heroku/plugin.rb
 INFO manager: Registered plugin: heroku
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/pushes/local-exec/plugin.rb
 INFO manager: Registered plugin: local-exec
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/pushes/noop/plugin.rb
 INFO manager: Registered plugin: noop
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/synced_folders/nfs/plugin.rb
 INFO manager: Registered plugin: NFS synced folders
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/synced_folders/rsync/plugin.rb
 INFO manager: Registered plugin: RSync synced folders
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/synced_folders/smb/plugin.rb
 INFO manager: Registered plugin: SMB synced folders
DEBUG global: Plugin loading is currently disabled.
 INFO vagrant: `vagrant` invoked: ["plugin", "install", "vagrant-vbguest", "--debug"]
DEBUG vagrant: Creating Vagrant environment
 INFO environment: Environment initialized (#<Vagrant::Environment:0x0000010134daa8>)
 INFO environment:   - cwd: /Users/<<USERNAME>>/<<WORKING_DIRECTORY>>
 INFO environment: Home path: /Users/<<USERNAME>>/.vagrant.d
DEBUG environment: Effective local data path:
 WARN environment: No local data path is set. Local data cannot be stored.
 INFO environment: Running hook: environment_plugins_loaded
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: environment_plugins_loaded #<Vagrant::Action::Builder:0x000001011fc2d0>
 INFO environment: Running hook: environment_load
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: environment_load #<Vagrant::Action::Builder:0x000001028812a8>
 INFO cli: CLI: [] "plugin" ["install", "vagrant-vbguest"]
DEBUG cli: Invoking command class: VagrantPlugins::CommandPlugin::Command::Root ["install", "vagrant-vbguest"]
DEBUG root: Invoking command class: VagrantPlugins::CommandPlugin::Command::Install ["vagrant-vbguest"]
 INFO loader: Loading configuration in order: [:home, :root]
DEBUG loader: Configuration loaded successfully, finalizing and returning
DEBUG push: finalizing
 INFO host: Autodetecting host type for [#<Vagrant::Environment: /Users/<<USERNAME>>/<<WORKING_DIRECTORY>>>]
DEBUG host: Trying: arch
DEBUG host: Trying: darwin
 INFO host: Detected: darwin!
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action:  #<Vagrant::Action::Builder:0x00000102110280>
 INFO warden: Calling IN action: #<VagrantPlugins::CommandPlugin::Action::InstallGem:0x0000010104d6c8>
 INFO interface: info: Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
DEBUG bundler: Enabling strict dependency enforcement
DEBUG bundler: Dependency list for installation:
 - vagrant-share > 0
 - vagrant-vbguest > 0
 - bigdecimal = 1.2.8
 - builder = 3.2.3
 - childprocess = 0.6.3
 - domain_name = 0.5.20170404
 - erubis = 2.7.0
 - ffi = 1.9.18
 - gssapi = 1.2.0
 - gyoku = 1.3.1
 - hashicorp-checkpoint = 0.1.4
 - http-cookie = 1.0.3
 - httpclient = 2.8.3
 - i18n = 0.8.0
 - io-console = 0.4.5
 - json = 1.8.3
 - listen = 3.1.5
 - little-plugger = 1.1.4
 - log4r = 1.1.10
 - logging = 2.2.2
 - mime-types = 3.1
 - mime-types-data = 3.2016.0521
 - multi_json = 1.12.1
 - net-scp = 1.2.1
 - net-sftp = 2.1.2
 - net-ssh = 4.1.0
 - netrc = 0.11.0
 - nori = 2.6.0
 - pkg-config = 1.1.9
 - psych = 2.1.0
 - rb-fsevent = 0.10.2
 - rb-inotify = 0.9.10
 - rb-kqueue = 0.2.5
 - rdoc = 4.2.1
 - rest-client = 2.0.2
 - ruby_dep = 1.3.1
 - rubyntlm = 0.6.2
 - rubyzip = 1.2.1
 - unf = 0.1.4
 - unf_ext = 0.0.7.4
 - vagrant = 1.9.7
 - wdm = 0.1.1
 - winrm = 2.2.3
 - winrm-elevated = 1.1.0
 - winrm-fs = 1.0.1
DEBUG bundler: Enabling user defined remote RubyGems sources
DEBUG bundler: Enabling default remote RubyGems sources
DEBUG bundler: Adding source - https://rubygems.org/
DEBUG bundler: Adding source - https://gems.hashicorp.com/
ERROR bundler: Failed to load configured plugin source `#<Gem::Source:0x000001021623a0>`: timed out (https://gems.hashicorp.com/specs.4.8.gz)
ERROR warden: Error occurred: Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

  timed out (https://gems.hashicorp.com/specs.4.8.gz)

Source: https://gems.hashicorp.com/
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<VagrantPlugins::CommandPlugin::Action::InstallGem:0x0000010104d6c8>
 INFO warden: Recovery complete.
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x0000010f70ac28>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::PluginSourceError: Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

  timed out (https://gems.hashicorp.com/specs.4.8.gz)

Source: https://gems.hashicorp.com/>
ERROR vagrant: Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

  timed out (https://gems.hashicorp.com/specs.4.8.gz)

Source: https://gems.hashicorp.com/
ERROR vagrant: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/bundler.rb:359:in `rescue in block in validate_configured_sources!'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/bundler.rb:350:in `block in validate_configured_sources!'
/opt/vagrant/embedded/lib/ruby/2.3.0/rubygems/source_list.rb:98:in `each'
/opt/vagrant/embedded/lib/ruby/2.3.0/rubygems/source_list.rb:98:in `each_source'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/bundler.rb:349:in `validate_configured_sources!'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/bundler.rb:285:in `internal_install'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/bundler.rb:106:in `install'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/plugin/manager.rb:62:in `block in install_plugin'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/plugin/manager.rb:72:in `install_plugin'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/plugin/action/install_gem.rb:29:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/plugin/command/base.rb:14:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/plugin/command/install.rb:32:in `block in execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/plugin/command/install.rb:31:in `each'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/plugin/command/install.rb:31:in `execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/plugin/command/root.rb:66:in `execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/cli.rb:42:in `execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/environment.rb:308:in `cli'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/bin/vagrant:138:in `<main>'
 INFO interface: error: Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

  timed out (https://gems.hashicorp.com/specs.4.8.gz)

Source: https://gems.hashicorp.com/
Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

  timed out (https://gems.hashicorp.com/specs.4.8.gz)

Source: https://gems.hashicorp.com/
 INFO interface: Machine: error-exit ["Vagrant::Errors::PluginSourceError", "Vagrant failed to load a configured plugin source. This can be caused\nby a variety of issues including: transient connectivity issues, proxy\nfiltering rejecting access to a configured plugin source, or a configured\nplugin source not responding correctly. Please review the error message\nbelow to help resolve the issue:\n\n  timed out (https://gems.hashicorp.com/specs.4.8.gz)\n\nSource: https://gems.hashicorp.com/"]
```
I removed sensible information (between `<<>>`).

### wget

```
➜ wget -v https://gems.hashicorp.com/specs.4.8.gz
--2017-07-20 14:19:12--  https://gems.hashicorp.com/specs.4.8.gz
Resolving gems.hashicorp.com... 2600:9000:2043:1000:b:36d6:3540:93a1, 2600:9000:2043:8e00:b:36d6:3540:93a1, 2600:9000:2043:7c00:b:36d6:3540:93a1, ...
Connecting to gems.hashicorp.com|2600:9000:2043:1000:b:36d6:3540:93a1|:443... failed: Operation timed out.
Connecting to gems.hashicorp.com|2600:9000:2043:8e00:b:36d6:3540:93a1|:443... failed: Operation timed out.
```

**Comment by florianb** [comment]
An interesting finding - fetching the file using:

```
wget -4 https://gems.hashicorp.com/specs.4.8.gz
curl https://gems.hashicorp.com/specs.4.8.gz
```

works - it seems like only the IPv6-download fails.

**Comment by florianb** [comment]
Here are my current A entries for `gems.hashicorp.com`:

```
dig gems.hashicorp.com A gems.hashicorp.com AAAA

; <<>> DiG 9.8.3-P1 <<>> gems.hashicorp.com A gems.hashicorp.com AAAA
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32892
;; flags: qr rd ra; QUERY: 1, ANSWER: 9, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;gems.hashicorp.com.		IN	A

;; ANSWER SECTION:
gems.hashicorp.com.	113	IN	CNAME	d3bqwsh65659ed.cloudfront.net.
d3bqwsh65659ed.cloudfront.net. 53 IN	A	54.192.44.171
d3bqwsh65659ed.cloudfront.net. 53 IN	A	54.192.44.186
d3bqwsh65659ed.cloudfront.net. 53 IN	A	54.192.44.189
d3bqwsh65659ed.cloudfront.net. 53 IN	A	54.192.44.142
d3bqwsh65659ed.cloudfront.net. 53 IN	A	54.192.44.30
d3bqwsh65659ed.cloudfront.net. 53 IN	A	54.192.44.204
d3bqwsh65659ed.cloudfront.net. 53 IN	A	54.192.44.229
d3bqwsh65659ed.cloudfront.net. 53 IN	A	54.192.44.250

;; Query time: 25 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Thu Jul 20 14:48:30 2017
;; MSG SIZE  rcvd: 207

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39899
;; flags: qr rd ra; QUERY: 1, ANSWER: 9, AUTHORITY: 0, ADDITIONAL: 8

;; QUESTION SECTION:
;gems.hashicorp.com.		IN	AAAA

;; ANSWER SECTION:
gems.hashicorp.com.	113	IN	CNAME	d3bqwsh65659ed.cloudfront.net.
d3bqwsh65659ed.cloudfront.net. 53 IN	AAAA	2600:9000:200e::b:36d6:3540:93a1
d3bqwsh65659ed.cloudfront.net. 53 IN	AAAA	2600:9000:200e:c800:b:36d6:3540:93a1
d3bqwsh65659ed.cloudfront.net. 53 IN	AAAA	2600:9000:200e:2400:b:36d6:3540:93a1
d3bqwsh65659ed.cloudfront.net. 53 IN	AAAA	2600:9000:200e:1400:b:36d6:3540:93a1
d3bqwsh65659ed.cloudfront.net. 53 IN	AAAA	2600:9000:200e:9a00:b:36d6:3540:93a1
d3bqwsh65659ed.cloudfront.net. 53 IN	AAAA	2600:9000:200e:ec00:b:36d6:3540:93a1
d3bqwsh65659ed.cloudfront.net. 53 IN	AAAA	2600:9000:200e:ee00:b:36d6:3540:93a1
d3bqwsh65659ed.cloudfront.net. 53 IN	AAAA	2600:9000:200e:3000:b:36d6:3540:93a1

;; ADDITIONAL SECTION:
d3bqwsh65659ed.cloudfront.net. 53 IN	A	54.192.44.189
d3bqwsh65659ed.cloudfront.net. 53 IN	A	54.192.44.142
d3bqwsh65659ed.cloudfront.net. 53 IN	A	54.192.44.30
d3bqwsh65659ed.cloudfront.net. 53 IN	A	54.192.44.204
d3bqwsh65659ed.cloudfront.net. 53 IN	A	54.192.44.229
d3bqwsh65659ed.cloudfront.net. 53 IN	A	54.192.44.250
d3bqwsh65659ed.cloudfront.net. 53 IN	A	54.192.44.171
d3bqwsh65659ed.cloudfront.net. 53 IN	A	54.192.44.186

;; Query time: 4 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Thu Jul 20 14:48:30 2017
;; MSG SIZE  rcvd: 431
```

**Comment by dominikzogg** [comment]
@briancain its seems to work now, but yeah could be a ipv6 problem, cause my ISP fully supports it

**Comment by florianb** [comment]
The issue is solved for me now, too (as well as the direct downloads with wget).

Would it make sense to consider implementing a fallback strategy in case of network troubles (f.e. reuse cached, local files)?

**Comment by drcraig** [comment]
I'm having this issue, too. Unclear if it's an IPv6 issue for me. I'm behind a corporate firewall that breaks and inspects SSL traffic. We have an internal mirror of rubygems, which in the past we've had success with when coupled with `--plugin-clean-sources --plugin-source https://gems.corp.my-company.com`. 

I get the same 

```
 INFO interface: error: Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Unable to resolve dependency: user requested 'vagrant-share (> 0)'
```

But I can install `vagrant-share` by itself just fine.

```
$ vagrant plugin install vagrant-share --plugin-clean-sources --plugin-source https://gems.corp.my-company.com/
Installing the 'vagrant-share' plugin. This can take a few minutes...
Installed the plugin 'vagrant-share (1.1.9)'!
```

**Comment by kikitux** [comment]
@drcraig seems your is a different issue, please open a new one.

You can try to use `SSL_CERT_FILE` to a cert that includes your proxy certs if needed.

Closing as seems the original issue ipv6 is fixed

**Comment by nickrttn** [comment]
I don't think it's fixed. I've just done a clean install of vagrant (a couple of days after this was closed) and I'm seeing the same errors while running `vagrant plugin install vagrant-bindfs`. 

Running `wget -v https://gems.hashicorp.com/specs.4.8.gz` (which resolves over IPv6) doesn't work for me, while `wget -4 https://gems.hashicorp.com/specs.4.8.gz` does.

**Comment by joshwertheim** [comment]
Same here...

**Comment by mattrose** [comment]
Same here.  
```
rome:vagrant_vsphere mattrose$ wget -v https://gems.hashicorp.com/specs.4.8.gz
--2017-08-22 11:23:23--  https://gems.hashicorp.com/specs.4.8.gz
Resolving gems.hashicorp.com... 2600:9000:2013:1a00:b:36d6:3540:93a1, 2600:9000:2013:fe00:b:36d6:3540:93a1, 2600:9000:2013:5200:b:36d6:3540:93a1, ...
Connecting to gems.hashicorp.com|2600:9000:2013:1a00:b:36d6:3540:93a1|:443... failed: Operation timed out.
```

**Comment by alainvanhoof** [comment]
Had the same issue on my Mac OSX, when I disabled IPv6, the issue was solved.

**Comment by florianb** [comment]
@kikitux, with all respect to your decision -- i don't understand why this issue is closed. It seems likely to me, that your ipv6 infrastructure is misconfigured.

**Comment by LordNoteworthy** [comment]
agree with @florianb. I have exactly the same issue. I run the last version of Vagrant and I just get a time out while trying to install vmware-workstation-plugin. I spent half a day trying to get around it and no luck.

**Comment by badams2527** [comment]
Just had the same issue on Windows 10. Disabling IPv6 also worked for me.

**Comment by numediaweb** [comment]
Had the same error: turns out my router blocked/filtered some ports! I disabled this filtering and I was able to install the plugins.

**Comment by 2bithacker** [comment]
Also experiencing this problem. At first I thought it might be a Path MTU Discovery problem, since I'm on an IPv6 tunnel, but it appears that I'm not even getting a SYN+ACK back from gems.hashicorp.com. So it seems it's not even listening on IPv6. Might want to pull those AAAAs till this is fixed.

https://gist.github.com/2bithacker/55c8890c523b5b40021e6a38a971a61c

**Comment by julmot** [comment]
I needed to switch my network to solve this issue (IP v6)

**Comment by joaosantos15** [comment]
Hello,

I was having this very same issue trying to install the aws plugin. After disabling IPv6, I ran 

`vagrant plugin install vagrant-aws --plugin-clean-sources --plugin-source https://rubygems.org`

As @drcraig  suggested and it worked 🎉

**Comment by amorZhu** [comment]
中国朋友，请看这里：
问题我已经解决了，参考：[https://segmentfault.com/n/1330000014282180](https://segmentfault.com/n/1330000014282180)

**Comment by wblucky** [comment]
@amorZhu the "Greatwall" is so big, thank you!

**Comment by EricAtHaufe** [comment]
I have the same issue with version 2.1.1 when attempting to install the vagrant-proxyconf-1.5.2.gem locally on my windows 10 machine.  

PS D:\HashiCorp\Vagrant\embedded\bin\gem> vagrant plugin install vagrant*.gem
Installing the 'vagrant-proxyconf-1.5.2.gem' plugin. ....

  timed out (https://api.rubygems.org/specs.4.8.gz)

Any ideas?

**Comment by EricAtHaufe** [comment]
o.k. solved my issue after reading Justins's blog:  [https://digitaldrummerj.me/vagrant-behind-proxy-server/](url)     

set http_proxy=http://yourproxyserver:port
set https_proxy=https://yourproxyserver:port

**Comment by pureboys** [comment]
感谢 @amorZhu 方法 不过有几个点需要改下：
1.请尽可能用比较新的 RubyGems 版本，建议 2.6.x 以上。
2. gems.ruby-china.org 更变为 gems.ruby-china.com/
3.  --plugin-clean-source 改为 --plugin-clean-sources
```
$ gem update --system # 这里请翻墙一下
$ gem -v
2.6.3
```
```
$ gem sources --add https://gems.ruby-china.com/ --remove https://rubygems.org/
$ gem sources -l
https://gems.ruby-china.com
# 确保只有 gems.ruby-china.com
```
vagrant plugin install vagrant-scp --plugin-clean-sources  --plugin-source https://gems.ruby-china.com/
可以正常使用

**Comment by SPascareli** [comment]
Just to help people that may still have this problem now, I had to disable IPv6 in my network interface, I'm using Debian, and disabling IPv6 via network manager graphical interface did not did the trick, I had to disable it via sysctl.conf file like described here:
https://superuser.com/questions/546788/how-to-disable-ipv6-on-debian-wheezy

I hope this helps someone.

**Comment by sandstad** [comment]
I just upgraded to Vagrant 2.2.5 and then plugins stopped working. (using VMWare Workstation plugin)

PS E:\HashiCorp> vagrant --version
Vagrant 2.2.5
I have disabled IPv6 on all interfaces to see if this were the problem. 
Proxy disabled and I'm able to download the file directly but are getting the error:

PS E:\HashiCorp> vagrant plugin install vagrant-vmware-desktop
Installing the 'vagrant-vmware-desktop' plugin. This can take a few minutes...
Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

  no such name (https://gems.hashicorp.com/specs.4.8.gz)

Source: https://gems.hashicorp.com/
